### ISSUE TITLE
Broken 2D Playground

### ISSUE THREAD

**Issue by jaidevshriram** [threestudio-project/threestudio#100]
Hey! I was trying to use the 2dplayground notebook in the base folder to test SDS on a 2D image - but got the following error:

```
TypeError: __call__() missing 4 required positional arguments: 'prompt_utils', 'elevation', 'azimuth', and 
'camera_distances'
```

I imagine the API has changed recently, could you suggest a fix to make the notebook work again? Thanks!

**Comment by bennyguo** [comment]
Thanks for pointing out! We'll fix this soon.

**Comment by jaidevshriram** [comment]
Hey, I managed to resolve this btw - can make a PR if you'd like - very few changes were required. I've also tested with VSD guidance. However, the images plotted are pretty saturated - for both SDS and VSD.

Example - VSD:

![image](https://github.com/threestudio-project/threestudio/assets/29925421/9a79110d-015b-4878-b53c-8e995e0938e7)

Example - SDS:

![image](https://github.com/threestudio-project/threestudio/assets/29925421/bb55b7a0-5fc4-4dbf-92e2-cecf8496559c)

I think this is because the image is getting clipped since the range is outside (0, 1). Is there a way to fix this for 2D sampling? Especially for VSD, I was expecting something like this from the paper:

<img width="1061" alt="image" src="https://github.com/threestudio-project/threestudio/assets/29925421/0977f427-73a2-4258-874b-f4f8784c8a25">

**Comment by jaidevshriram** [comment]
Thanks! That did fix it - here is an img with SDS on the latent space:

<img width="225" alt="image" src="https://github.com/threestudio-project/threestudio/assets/29925421/18105ae5-0336-435d-939a-b7f098959915">

I've also made a PR to fix it. As a related question, I see that the dreamfusion pipeline does not use RGB as latent (seems to optimise in the RGB space). How do you obtain good results in that case if 2D SDS in RGB space does not? Thanks!!

**Comment by thuliu-yt16** [comment]
Dreamfusion uses deepfloyd-if as the prior model which directly denoises images on pixel space.

**Comment by jaidevshriram** [comment]
Oh I meant in the context of dreamfusion-sd which is present in the config file

**Comment by thuliu-yt16** [comment]
Dreamfusion with sd performs much worse than that with deepfloyd-if. For the 2D and 3D case for SDS/VSD, I don't think they're quite equivalent and are bound to give the same effects. Just talking about 2D case, you will get totally different results if using different activation methods, not to mention how different the way we parameterize the 3D nerf from 2D canvas.  But in general, I agree that we can get some insights from the 2D situation, such as comparing different losses.

**Comment by jaidevshriram** [comment]
I see, that's helpful. Thanks!
