### ISSUE TITLE
Mesh Refinement Stage for ProlificDreamer

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#107]
Hi! How can I experiment with the Mesh refinement stage of ProlificDreamer? The README states that it is already implemented, and I see a config for it, so I am curious on how I can use it. Thanks!

**Comment by bennyguo** [comment]
Hi! You can use [this branch](https://github.com/threestudio-project/threestudio/tree/finalize-prolific-dreamer) for all the 3 stages of ProlificDreamer. It will be merged soon.

**Comment by ayaanzhaque** [comment]
Great, thank you!

**Comment by xinfeixiang1** [comment]
one question is that why use 3 stages of ProlificDreamer? i think the first and the second step could be merged ?

**Comment by bennyguo** [comment]
> one question is that why use 3 stages of ProlificDreamer? i think the first and the second step could be merged ?

The mesh extracted from the first stage is noisy. The second stage is intended to fix this and produce good mesh geometry.
