### ISSUE TITLE
Memory for 512 ProlificDreamer

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#108]
Do you all have any details on how much memory is required to run the 512 resolution ProlificDreamer? I keep getting OOM errors and my GPU has 48GB of memory.

**Comment by UMGrain** [comment]
> Do you all have any details on how much memory is required to run the 512 resolution ProlificDreamer? I keep getting OOM errors and my GPU has 48GB of memory.

+1

**Comment by bennyguo** [comment]
Hi guys. It's a known issue. Sorry I didn't point this out in README. I suspect it's because we use far more ray samples than the original paper, which easily causes OOM in early training. Could you try a lower num_ray_samples (default 512) and see if you get any luck? This could be a temporary solution and I'll try to come up with a better one later.

**Comment by ayaanzhaque** [comment]
Sounds good, will try it and let you know.

**Comment by ayaanzhaque** [comment]
@bennyguo Interesting solution! Curious to see how that works.

In terms for GPUs, will this speed up the iters/sec?

Also, just curious, have you thought about using Deepfloyd for ProlificDreamer? I assume it would be quite slow, and maybe there aren't any LoRA implementations of Deepfloyd out yet, I'm not sure.

**Comment by bennyguo** [comment]
Setting `--gpu 0,1` will make each GPU process a batch, and will not speed up iters/sec. There's currently no easy way to split a batch into multiple GPUs (i.e., each GPU only renders part of the image). Although iters/sec is not getting any larger, you can train for less iterations, which is also a speedup :) 

I do intent to try ProlificDreamer on DeepFloyd but haven't got the time yet. It shouldn't be much slower than ProlificDreamer+SD, and yeah I don't think there are any LoRA implementations of DeepFloyd (although it should be easy in diffusers).

**Comment by ayaanzhaque** [comment]
Ah ok, sounds good, thanks for the info.

For writing a LoRA implementation, can you point to where you found the LoRA implementation for SD? I'm interested in writing a LoRA implementation for Deepfloyd, but am pretty new to it so not sure how to get started.

**Comment by bennyguo** [comment]
In my VSD implementation, I directly take the LoRA implementation [here](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py#L819). I think it works by iterating over all layers and adding LoRA modules as `AttnProcsLayers`. Looking forward to your DeepFloyd-LoRA!

**Comment by bennyguo** [comment]
Hey guys, I've opened a PR to enable progressively increasing rendering resolution: we first train on 64x64 rendering for the first 1,000 iterations, then switch to 512x512 rendering for the remaining iterations. This should drastically save VRAM as the empty space is pruned in early steps. Could you try [this branch](https://github.com/threestudio-project/threestudio/tree/progressive-resolution) and see if you could successfully train using a 40GB GPU? Note that you DON'T need to specify `data.width=512` and `data.height=512` in the command line, as it is now `data.width=[64,512]` and `data.height=[64,512]` for this progressive training strategy.

**Comment by bennyguo** [comment]
Yes it's 64x64 VSD. Are you tested  on a 40GB GPU? Could you increase the number 1000 in data.resolution_milestones to 5000 and try again?

**Comment by ayaanzhaque** [comment]
How much memory does the standard ProlificDreamer currently in the main branch take? I'm training it and its taking 40gb of memory, which seems quite high...

**Comment by ayaanzhaque** [comment]
Does it use 256x256 by default or 64x64?

**Comment by bennyguo** [comment]
It uses 256x256 by default. It's the same problem as with 512x512: if we could get the progressive strategy working, we should be able to train with much less VRAM.

**Comment by ayaanzhaque** [comment]
Will test it in a bit!

**Comment by ayaanzhaque** [comment]
I'm training it now, will let you know how it goes.

**Comment by ayaanzhaque** [comment]
The first stage takes ~33GB of memory, and the second stage also takes around ~33GB of memory. I'll let it keep training, but do you know if this produces overall better results? Otherwise, it looks like it works fine.

**Comment by ayaanzhaque** [comment]
Question: is there a way to load in a dreamfusion model into the prolificdreamer pipeline?

**Comment by ayaanzhaque** [comment]
Also, by your estimations, how long does just phase 1 (25k iters) of the standard ProlificDreamer take at the default resolution?

**Comment by bennyguo** [comment]
> The first stage takes ~33GB of memory, and the second stage also takes around ~33GB of memory. 
Great to hear that the first stage now works under 48GB VRAM. However the second stage should not take that much VRAM 😂 It only takes ~7GB VRAM for the second stage in my experiments.

> Question: is there a way to load in a dreamfusion model into the prolificdreamer pipeline?
Just set `system.geometry_convert_from=path/to/your/dreamfusion/checkpoint system.geometry_convert_inherit_texture=false`. In this way, you can load a dreamfusion model into any of the 3 stages of the prolificdreamer pipeline. Note that you may need to change `data.camera_distance_range` and `system.model.radius` as the dreamfusion pipeline and the prolificdreamer pipeline use different camera configurations.

> Also, by your estimations, how long does just phase 1 (25k iters) of the standard ProlificDreamer take at the default resolution?
It takes ~4.5 hours on a single RTX 3090.

**Comment by ayaanzhaque** [comment]
Ah sorry, by second stage I mean the second part of stage 1, where it trains at 512x512 resolution. The mesh geometry part is definitely less memory.

Thanks for the details about the DreamFusion loading.
