### ISSUE TITLE
Cache Text Embeddings

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#112]
Is there a reason the text embeddings are re-created in every forward pass? Even if they are view-dependent, can they just be pre-computed? I believe this would lead to significant speed ups. Please let me know.

**Comment by bennyguo** [comment]
They are not computed every time you run. If you have trained for some prompt, the text embeddings are cached in .threestudio_cache/. You could see threestudio/models/prompt_processors/base.py for implementation details 😄

**Comment by ayaanzhaque** [comment]
Ah ok, sounds good, thanks!
