### ISSUE TITLE
DreamFusion-IF with higher resolution

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#114]
Will it help performance to train dreamfusion-IF with a higher resolution, say 256? I assume the image is resized to 64x64 before inputting into IF, but I'm not exactly sure. Any insights would be helpful

**Comment by bennyguo** [comment]
I didn't try this but since the rendered image is first downsampled to 64x64 and then fed to the diffusion model I don't think this will bring significant quality improvement. The ideally way would be to use the upsampling stages in DeepFloyd but that's not very trivial.

**Comment by ayaanzhaque** [comment]
Sounds good, ya if its just being resized and IF works at 64x64, then no need to use higher resolution. Thanks!
