### ISSUE TITLE
replace functions from igl

### ISSUE THREAD

**Issue by yankeesong** [threestudio-project/threestudio#115]
Is it possible to rewrite functions from igl? I'm using a linux ppc64le system, and it seems I cannot install libigl from either pip or conda.
The three functions are fast_winding_number_for_meshes, point_mesh_squared_distance, read_obj

**Comment by bennyguo** [comment]
Hi! We simply took these code snippets from the official Latent-NeRF repo. It's possible to re-write these functions using other libraries but you may want to try installing libigl from source first, see https://github.com/libigl/libigl-python-bindings#installation:
<img width="874" alt="image" src="https://github.com/threestudio-project/threestudio/assets/19284678/9766c5da-c919-4c58-84dc-0f56e22670cf">
