### ISSUE TITLE
Mesh --> NeRF

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#116]
Is there any support currently to go from an initial Mesh to a NeRF initialization? There's obviously NeRF --> Mesh, but can this codebase go the other way around?

**Comment by bennyguo** [comment]
Converting a mesh to NeRF can be difficult, but it's possible to use the shape-guided loss as in `sketchshape.yaml`, which will constrain the NeRF to have a similar shape to a given mesh.

**Comment by bennyguo** [comment]
@DSaurus just reminded me that we could render multi-view images of the mesh and train a NeRF. We could add this feature.

**Comment by ayaanzhaque** [comment]
Ah that makes sense, is there a way currently to train a normal NeRF in threestudio?

**Comment by DSaurus** [comment]
Hi @ayaanzhaque,

I have implemented a multiview dataset in Control4D branch. Now I can successfully train a NeRF in my rendering dataset. I also test it using your instrcutnerf2nerf dataset. However, NeRF fails to reconstruct the scene, which seems caused by the wrong origin of the world coordinate.

**Comment by ayaanzhaque** [comment]
Ya that makes sense, Instruct-NeRF2NeRF uses nerfstudio which uses COLMAP, so maybe the coordinates and reconstructions are different

**Comment by claforte** [comment]
Maybe it would make sense soon to optionally rely on NerfStudio from this project, to take advantage of the new methods they add, e.g. K-Planes. Given they are both using NerfAcc, it sounds like this might be relatively straightforward...?

**Comment by ayaanzhaque** [comment]
I think the Nerfstudio repository is meant to be a stand-alone repo, in the sense that they have their own trainers, pipelines, datamanagers and more. But in the case of Threestudio, I don't think most of the Nerfstudio features are useful for this repository. I also don't believe Nerfstudio can do what I asked in this issue, which is convert Mesh to NeRF.
