### ISSUE TITLE
Saving ProlificDreamer result as mesh problem: no albedo texture found

### ISSUE THREAD

**Issue by ericwudocomoi** [threestudio-project/threestudio#117]
Thanks for this great project!

I followed the 3 stages of training/refining of ProlificDreamer and successfully generated a short mp4 video of an awesome pineapple. But when I try to export the result to mesh (also following the instruction in Readme), I got:

`[WARNING] save_texture is True but no albedo texture found, using default white texture`.

I looked at the resulting mesh, indeed there is no texture but geometry looks valid. Is mesh saving not implemented for ProlificDreamer yet?

Any suggestion is highly appreciated!

**Comment by bennyguo** [comment]
Thanks for reporting this! This is because the `export` function for `no-material` has not been implemented. I've already fixed this in the latest commit, please try again!

<img width="654" alt="image" src="https://github.com/threestudio-project/threestudio/assets/19284678/6d807bff-5a0c-46ea-adc7-682501de3113">

**Comment by ericwudocomoi** [comment]
Indeed, the latest addition to `no_material.py` fixed the problem. I can now get mesh similar to yours. Thank you very much!

**Comment by ZedFu** [comment]
Thanks for this great project!

I also encountered a similar problem when I ran latentnerf code. I followed the 2 stages of training/refining of latentnerf and successfully generated a short mp4 video. But when I try to export the result to mesh (also following the instruction in Readme), I got:
[WARNING] save_texture is True but no albedo texture found, using default white texture.

this is my code :

```
python launch.py --config configs/latentnerf.yaml --train --gpu 0 system.prompt_processor.prompt="a chimpanzee sitting on a wooden bench"

python launch.py --config configs/latentnerf-refine.yaml --train --gpu 0 system.prompt_processor.prompt="a chimpanzee sitting on a wooden bench" system.weights=./outputs/latentnerf/a_chimpanzee_sitting_on_a_wooden_bench@20240222-173141/ckpts/last.ckpt

python launch.py --config .outputs/latentnerf-refine/a_chimpanzee_sitting_on_a_wooden_bench@20240222-180811/configs/parsed.yaml --export --gpu 0 resume=./outputs/latentnerf refine/a_chimpanzee_sitting_on_a_wooden_bench@20240222-180811/ckpts/last.ckpt system.exporter_type=mesh-exporter 
```

I looked at the resulting mesh, indeed there is no texture but geometry looks valid. I am very confused about that “ no albedo texture” while the latentnerf-refine config material_type is "sd-latent-adapter-material".

Any suggestion is highly appreciated!

**Comment by WakyWakyWayne** [comment]
> Thanks for this great project!
> 
> I also encountered a similar problem when I ran latentnerf code. I followed the 2 stages of training/refining of latentnerf and successfully generated a short mp4 video. But when I try to export the result to mesh (also following the instruction in Readme), I got: [WARNING] save_texture is True but no albedo texture found, using default white texture.
> 
> this is my code :
> 
> ```
> python launch.py --config configs/latentnerf.yaml --train --gpu 0 system.prompt_processor.prompt="a chimpanzee sitting on a wooden bench"
> 
> python launch.py --config configs/latentnerf-refine.yaml --train --gpu 0 system.prompt_processor.prompt="a chimpanzee sitting on a wooden bench" system.weights=./outputs/latentnerf/a_chimpanzee_sitting_on_a_wooden_bench@20240222-173141/ckpts/last.ckpt
> 
> python launch.py --config .outputs/latentnerf-refine/a_chimpanzee_sitting_on_a_wooden_bench@20240222-180811/configs/parsed.yaml --export --gpu 0 resume=./outputs/latentnerf-refine/a_chimpanzee_sitting_on_a_wooden_bench@20240222-180811/ckpts/last.ckpt system.exporter_type=mesh-exporter 
> ```
> 
> I looked at the resulting mesh, indeed there is no texture but geometry looks valid. I am very confused about that “ no albedo texture” while the latentnerf-refine config material_type is "sd-latent-adapter-material".
> 
> Any suggestion is highly appreciated! <img alt="PixPin_2024" width="999" src="https://private-user-images.githubusercontent.com/43996254/306984656-70efb8df-1b20-443c-922e-8d1e3fbce688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjMxMjQsIm5iZiI6MTcxNTIyMjgyNCwicGF0aCI6Ii80Mzk5NjI1NC8zMDY5ODQ2NTYtNzBlZmI4ZGYtMWIyMC00NDNjLTkyMmUtOGQxZTNmYmNlNjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyNDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTlhZjA5Y2NkMmZmODI0YTcwYmQ0MzhhMzA5ZWQ3M2YwOWE2MDA4MTljYmEwMDg1ODE0NmJjM2JmZTBjODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G1xj0wDMyI5t71PrhLolkHGyHWydejh7bP7bRhvRErc">

sd-latent-adapter-material.py doesn't have export function, add this
    def export(self, features: Float[Tensor, "*N Nf"], **kwargs) -> Dict[str, Any]:
        color = self(features, **kwargs).clamp(0, 1)
        assert color.shape[-1] >= 3, "Output color must have at least 3 channels"
        if color.shape[-1] > 3:
            threestudio.warn(
                "Output color has >3 channels, treating the first 3 as RGB"
            )
        return {"albedo": color[..., :3]}

**Comment by WakyWakyWayne** [comment]
sd-latent-adapter-material.py doesn't have export function, add this

def export(self, features: Float[Tensor, "*N Nf"], **kwargs) -> Dict[str, Any]:
        color = self(features, **kwargs).clamp(0, 1)
        assert color.shape[-1] >= 3, "Output color must have at least 3 channels"
        if color.shape[-1] > 3:
            threestudio.warn(
                "Output color has >3 channels, treating the first 3 as RGB"
            )
        return {"albedo": color[..., :3]}
