### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by YoujiaZhang** [threestudio-project/threestudio#118]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/threestudio/launch.py:180 in <module>                                                      │
│                                                                                                  │
│   177                                                                                            │
│   178                                                                                            │
│   179 if __name__ == "__main__":                                                                 │
│ ❱ 180 │   main()                                                                                 │
│   181                                                                                            │
│                                                                                                  │
│ /root/threestudio/launch.py:82 in main                                                           │
│                                                                                                  │
│    79 │   │                                                                                      │
│    80 │   │   install_import_hook("threestudio", "typeguard.typechecked")                        │
│    81 │                                                                                          │
│ ❱  82 │   import threestudio                                                                     │
│    83 │   from threestudio.systems.base import BaseSystem                                        │
│    84 │   from threestudio.utils.callbacks import (                                              │
│    85 │   │   CodeSnapshotCallback,                                                              │
│                                                                                                  │
│ /root/threestudio/threestudio/__init__.py:36 in <module>                                         │
│                                                                                                  │
│   33 │   logger.warn(*args, **kwargs)                                                            │
│   34                                                                                             │
│   35                                                                                             │
│ ❱ 36 from . import data, models, systems                                                         │
│   37                                                                                             │
│                                                                                                  │
│ /root/threestudio/threestudio/data/__init__.py:1 in <module>                                     │
│                                                                                                  │
│ ❱ 1 from . import co3d, image, uncond                                                            │
│   2                                                                                              │
│                                                                                                  │
│ /root/threestudio/threestudio/data/co3d.py:17 in <module>                                        │
│                                                                                                  │
│    14 from torch.utils.data import DataLoader, Dataset, IterableDataset                          │
│    15                                                                                            │
│    16 from threestudio import register                                                           │
│ ❱  17 from threestudio.data.uncond import (                                                      │
│    18 │   RandomCameraDataModuleConfig,                                                          │
│    19 │   RandomCameraDataset,                                                                   │
│    20 │   RandomCameraIterableDataset,                                                           │
│                                                                                                  │
│ /root/threestudio/threestudio/data/uncond.py:11 in <module>                                      │
│                                                                                                  │
│     8 from torch.utils.data import DataLoader, Dataset, IterableDataset                          │
│     9                                                                                            │
│    10 from threestudio import register                                                           │
│ ❱  11 from threestudio.utils.config import parse_structured                                      │
│    12 from threestudio.utils.misc import get_device                                              │
│    13 from threestudio.utils.ops import (                                                        │
│    14 │   get_mvp_matrix,                                                                        │
│                                                                                                  │
│ /root/threestudio/threestudio/utils/__init__.py:1 in <module>                                    │
│                                                                                                  │
│ ❱ 1 from . import base                                                                           │
│   2                                                                                              │
│                                                                                                  │
│ /root/threestudio/threestudio/utils/base.py:7 in <module>                                        │
│                                                                                                  │
│    4 import torch.nn as nn                                                                       │
│    5                                                                                             │
│    6 from threestudio.utils.config import parse_structured                                       │
│ ❱  7 from threestudio.utils.misc import get_device, load_module_weights                          │
│    8 from threestudio.utils.typing import *                                                      │
│    9                                                                                             │
│   10                                                                                             │
│                                                                                                  │
│ /root/threestudio/threestudio/utils/misc.py:5 in <module>                                        │
│                                                                                                  │
│     2 import os                                                                                  │
│     3 import re                                                                                  │
│     4                                                                                            │
│ ❱   5 import tinycudann as tcnn                                                                  │
│     6 import torch                                                                               │
│     7 from packaging import version                                                              │
│     8                                                                                            │
│                                                                                                  │
│ /root/anaconda3/lib/python3.9/site-packages/tinycudann/__init__.py:9 in <module>                 │
│                                                                                                  │
│    6 # distribution of this software and related documentation without an express                │
│    7 # license agreement from NVIDIA CORPORATION is strictly prohibited.                         │
│    8                                                                                             │
│ ❱  9 from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network,    │
│   10                                                                                             │
│   11 __all__ = ["free_temporary_memory", "NetworkWithInputEncoding", "Network", "Encoding"]      │
│   12                                                                                             │
│                                                                                                  │
│ /root/anaconda3/lib/python3.9/site-packages/tinycudann/modules.py:50 in <module>                 │
│                                                                                                  │
│    47 │   │   continue                                                                           │
│    48 │                                                                                          │
│    49 │   try:                                                                                   │
│ ❱  50 │   │   _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")                       │
│    51 │   │   if cc != system_compute_capability:                                                │
│    52 │   │   │   warnings.warn(f"tinycudann was built for lower compute capability ({cc}) tha   │
│    53 │   │   break                                                                              │
│                                                                                                  │
│ /root/anaconda3/lib/python3.9/importlib/__init__.py:127 in import_module                         │
│                                                                                                  │
│   124 │   │   │   if character != '.':                                                           │
│   125 │   │   │   │   break                                                                      │
│   126 │   │   │   level += 1                                                                     │
│ ❱ 127 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   128                                                                                            │
│   129                                                                                            │
│   130 _RELOADING = {}                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: /root/anaconda3/lib/python3.9/site-packages/tinycudann_bindings/_70_C.cpython-39-x86_64-linux-gnu.so: undefined symbol:
_ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE

**Comment by DSaurus** [comment]
Hi, 

It seems caused by the wrong installation of tiny-cuda-nn. You can refer to this [issue](https://github.com/NVlabs/tiny-cuda-nn/issues/254).

**Comment by YoujiaZhang** [comment]
Thanks for your answer! It solved my problem and I found it because: I first executed `pip install torch==1.12.1+cu113`, then executed `pip install -r requirements.txt` and modified the installed version of pytorch
