### ISSUE TITLE
Camera Embedding Details

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#122]
How were the embedding sizes [here](https://github.com/threestudio-project/threestudio/blob/main/threestudio/models/guidance/stable_diffusion_vsd_guidance.py#L149) chosen? Where can I learn more about diffusion class embeddings?

**Comment by thuliu-yt16** [comment]
Just the same as the class embedding dimension so that they can be added. For detailed about class embedding, you can refer to `diffusers.UNet2DConditionModel`.

**Comment by ayaanzhaque** [comment]
Got it, thanks!
