### ISSUE TITLE
LoRA Guidance Scale

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#124]
How was the guidance scale for the LoRA model chosen? I see it is set at 1 as opposed to the standard 7.5.

**Comment by ayaanzhaque** [comment]
Did the paper have any details about how they did conditioning in this case? I'm finding that the choice of guidance scale makes a measurable difference in performance.

**Comment by ayaanzhaque** [comment]
@thuliu-yt16 I see you are working on a LoRA implementation for VSD, have you gotten any good results with it yet? I am working on something similar but I can't seem to get the LoRA samples to look correct. They seem to be incredibly saturated and have a green noise pattern. Let me know

**Comment by thuliu-yt16** [comment]
Actually, I am working on deepfloyd-if's VSD version, I get something with similar quality with Stable Diffusion before annealing the noise level. I don't see saturated and over-noisy results. But after annealing t, the results are with wired colors. I guess it is because deepfloyd-if is trained with noise-prediction rather than v-prediction mode.

**Comment by ayaanzhaque** [comment]
Ah interesting. Do you have any results you could share? Also, is there any solution to getting rid of the weird colors?

**Comment by thuliu-yt16** [comment]
Before annealing

<img width="885" alt="截屏2023-06-16 下午12 20 27" src="https://github.com/threestudio-project/threestudio/assets/27289204/e24c41f2-c2b8-4ae3-8e35-3bd22524ce06">

After

<img width="889" alt="截屏2023-06-16 下午12 20 06" src="https://github.com/threestudio-project/threestudio/assets/27289204/c5365b2b-dc69-4084-ab30-e88d791f0a2d">

We guess the background may affect the color significantly but not tested yet. If you are interested in it, you could try the code in deepfloyd-vsd branch with/without random background augmentation or with/without color-fixed background.

**Comment by ayaanzhaque** [comment]
Very interesting results. Thanks for sharing, I'll give your suggestions a shot!

**Comment by yuefeng21** [comment]
> Before annealing
> 
> <img alt="截屏2023-06-16 下午12 20 27" width="885" src="https://private-user-images.githubusercontent.com/27289204/246315145-e24c41f2-c2b8-4ae3-8e35-3bd22524ce06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODg0OTUsIm5iZiI6MTcwNjI4ODE5NSwicGF0aCI6Ii8yNzI4OTIwNC8yNDYzMTUxNDUtZTI0YzQxZjItYzJiOC00YWUzLThlMzUtM2JkMjI1MjRjZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE2NTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZjk3NGM1NjEzMmYyNmRiMmIyMGQ2Zjc0YjE2ZGVkZTMwZjlmOTU0YTNjYWY5NzE3YmVkMWRkMjFmZjI0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XSkqRs_5Wm-4ud50mxxr06Bz9knQGtympo_9KYcjSWM">
> After
> 
> <img alt="截屏2023-06-16 下午12 20 06" width="889" src="https://private-user-images.githubusercontent.com/27289204/246315108-c5365b2b-dc69-4084-ab30-e88d791f0a2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODg0OTUsIm5iZiI6MTcwNjI4ODE5NSwicGF0aCI6Ii8yNzI4OTIwNC8yNDYzMTUxMDgtYzUzNjViMmItZGM2OS00MDg0LWFiMzAtZTg4ZDc5MWYwYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE2NTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3M2Y1MGJiMWZkOTY3N2JkMWUxNTY0MmNhZGI1Yjk0ODMxNjhhOWM2YTQ1NmU0NzI0OWVjMDc0Mzk4NzlhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zsJwxcB_v3JYzak6Jt2jwZZZ62ea-QOmDRCNG9eq5K4">
> We guess the background may affect the color significantly but not tested yet. If you are interested in it, you could try the code in deepfloyd-vsd branch with/without random background augmentation or with/without color-fixed background.

Just a follow up, have this weired colors in IF vsd been solved?
