### ISSUE TITLE
Render out different views + video during training

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#125]
is there an easy way to render of different camera angles during training, as well as render out the 360 video every 2k iterations?

**Comment by MrTornado24** [comment]
Hi, you can rewrite the function ```on_validation_epoch_end``` in the system files to render a 360 video referring to https://github.com/threestudio-project/threestudio/blob/1de1f157aaf34307bb65c05c6bba9a46a03efdcc/threestudio/systems/zero123.py#L332.

The number of views can be set by ```data.n_val_views```, e.g. ```data.n_val_views=100```; eval interval can be set by ```trainer.val_check_interval=2000```

**Comment by ayaanzhaque** [comment]
Thanks!
