### ISSUE TITLE
Lora noise And pretrain SD noise

### ISSUE THREAD

**Issue by silence401** [threestudio-project/threestudio#126]
Why lora's noise needs to do the following calculation and then calculate the loss with SD's noise;
https://github.com/threestudio-project/threestudio/blob/1de1f157aaf34307bb65c05c6bba9a46a03efdcc/threestudio/models/guidance/stable_diffusion_vsd_guidance.py#L512

**Comment by thuliu-yt16** [comment]
This is only required when the unet is in v-prediction mode, which means the unet output is the velocity. To get noise from velocity, we need the conversion. You can refer to [Progressive Distillation for Fast Sampling of Diffusion Models](http://arxiv.org/abs/2202.00512) for details, which said

<img width="605" alt="截屏2023-06-14 下午2 15 25" src="https://github.com/threestudio-project/threestudio/assets/27289204/c66230f4-c10a-4ffd-bd87-f24fb0a21fa0">

**Comment by silence401** [comment]
Thanks for your replay!
in diffuses scheduler get_velcocity is
v = sqrt_alpha * noise - sqrt_sigma * latents
to get noise is then
noise = (v + sqrt_sigma * latents) / sqrt_alpha?

**Comment by thuliu-yt16** [comment]
Nope, x here is the real image （x_0）.
We have

$$
v = \alpha_t  \epsilon - \sigma_t x_0
$$

and

$$
x_t=\alpha_t x_0 + \sigma_t  \epsilon
$$

Solve the equation, and given 

$$
\sigma_t^2+\alpha_t^2 = 1
$$

You will get the same format as the code.

**Comment by silence401** [comment]
Got it, Thanks!
