### ISSUE TITLE
Wrong CFG implementation

### ISSUE THREAD

**Issue by jzhangbs** [threestudio-project/threestudio#127]
Classifier free guidance should be calculated as `noise_pred = uncond + cfg * (cond - uncond)`, but it seems all the guidance modules are implemented as `noise_pred = cond + cfg * (cond - uncond)`. e.g. https://github.com/threestudio-project/threestudio/blob/main/threestudio/models/guidance/stable_diffusion_guidance.py#L240

Fortunately this problem is not significant when cfg is large, and all the results look good so far.

**Comment by thuliu-yt16** [comment]
They are just the same when you replace cfg with cfg + 1 for the `uncond` first version. We follow [the original paper](http://arxiv.org/abs/2207.12598) to implement it. IMO, both implementations are ok. You can try whether the quality gets improved with cfg=7.5 and the `uncond` first version.

**Comment by jzhangbs** [comment]
Ah yes they are indeed equivalent. Thanks for the explanation.
