### ISSUE TITLE
RuntimeError: OpenGL 4.4 or later is required 

### ISSUE THREAD

**Issue by tmrjlu** [threestudio-project/threestudio#128]
Use a single card ：
python launch.py --config configs/prolificdreamer-geometry.yaml --train --gpu 0  system.prompt_processor.prompt="a pineapple" system.geometry_convert_from=~path/threestudio/outputs/prolificdreamer/a_pineapple/ckpts/last.ckpt
The program executes normally.

Use a multi cards ：
python launch.py --config configs/prolificdreamer-geometry.yaml --train --gpu 0,1,2,3 system.prompt_processor.prompt="a pineapple" system.geometry_convert_from=~path/threestudio/outputs/prolificdreamer/a_pineapple/ckpts/last.ckpt

The program fails, and the error is as follows:

RuntimeError: OpenGL 4.4 or later is required 
Is this phenomenon normal?

**Comment by DSaurus** [comment]
Hi,

You can try to modify "gl" to "cuda" in your config.
···
 renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: gl
···
->
···
 renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: cuda
···

**Comment by tmrjlu** [comment]
> Hi,
> 
> You can try to modify "gl" to "cuda" in your config.
> 
> ```
>  renderer_type: "nvdiff-rasterizer"
>   renderer:
>     context_type: gl
> ```
> 
> ->
> 
> ```
>  renderer_type: "nvdiff-rasterizer"
>   renderer:
>     context_type: cuda
> ```

thank you!  Solved my problem
