### ISSUE TITLE
readme bug/typo @ setting prompt debiasing

### ISSUE THREAD

**Issue by GGGHSL** [threestudio-project/threestudio#132]
https://github.com/threestudio-project/threestudio/blob/abfe2139cb4728bd1447f4ca85d81fdc7bf414e0/README.md?plain=1#L429
`system.prompt_processor.enable_prompt_debiasing=true` >> `system.prompt_processor.use_prompt_debiasing=true`

**Comment by bennyguo** [comment]
Thank you for pointing this out! Would you be interested in opening a PR to fix this?
