### ISSUE TITLE
D-SDS and Perp-Neg for VSD guidance

### ISSUE THREAD

**Issue by yankeesong** [threestudio-project/threestudio#135]
Are they also compatible for VSD guidance? I see currently they are not supported.

**Comment by tmrjlu** [comment]
> Are they also compatible for VSD guidance? I see currently they are not supported.

If it is not implemented, then there is no difference from magic3D

**Comment by yankeesong** [comment]
I think there's a misunderstanding. I'm refering to the D-SDS and Perp-Neg algorithms for reducing the Janus problem.

**Comment by bennyguo** [comment]
Hi! They're currently not implemented for VSD but you can try to implement them according to their implementation in `stable-diffusion-guidance`. Note that Perp-Neg for VSD should only be adopted to the pretrained model as the LoRA model takes view-INDEPENDENT prompt and camera pose as input.

**Comment by yankeesong** [comment]
Following up on this. It seems that the original ProlificDreamer paper did not augment view-dependent prompt into the pretrained model. If we use view-dependent prompt then we would have different y value in their equation (9), which doesn't quite make sense right?
