### ISSUE TITLE
token_merging error！How can i do it?

### ISSUE THREAD

**Issue by tmrjlu** [threestudio-project/threestudio#136]
scipt：
python launch.py --config configs/prolificdreamer.yaml --train --gpu 5,6 system.prompt_processor.prompt="a DSLR photo of a blue car" data.batch_size=1 data.width=256 data.height=256 system.guidance.token_merging=true

TypeError: __init__() got an unexpected keyword argument 'token_merging'

**Comment by bennyguo** [comment]
Hi! As is demonstrated in the documentation, `token_merging` only supports `stable-diffusion-guidance`, so you can't use it in ProlificDreamer :(
