### ISSUE TITLE
problem about the trained Lora outputs

### ISSUE THREAD

**Issue by mindazhao** [threestudio-project/threestudio#141]
Thanks for the great job for prolificdreamer. However, when I trained VSD for 2D text-to-image and output the results of Lora with DDIM,  I find the results show such noises as Fig 1, but the outputs of optimized image is great as Fig. 2. Moreover, I also find the implementation of Lora initialization is not zero-weight, is it the reason I cannot get correct results of Lora? Thanks!

![unet_lora_48](https://github.com/threestudio-project/threestudio/assets/43086688/9915b225-c1c0-4adf-ae35-0330bf345dfd)

![two_d_img_9500](https://github.com/threestudio-project/threestudio/assets/43086688/4124c427-58ed-4a6f-b1df-71ade61b566e)

**Comment by thuliu-yt16** [comment]
Could you try other samplers, e.g. DDPM or DPMSolverMultiStep? 

I think the lora layers are initialized as zero output actually if I remember correctly. You may check it in [LoRAAttnProcessor](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_processor.py#L537) and [LoRALinearLayer](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_processor.py#L522)

**Comment by mindazhao** [comment]
> Could you try other samplers, e.g. DDPM or DPMSolverMultiStep?
> 
> I think the lora layers are initialized as zero output actually if I remember correctly. You may check it in [LoRAAttnProcessor](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_processor.py#L537) and [LoRALinearLayer](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_processor.py#L522)

Thanks sir, I find the problem is the pretrained_model_name_or_path_lora=stabilityai/stable-diffusion-2-1 which is trained with 768 resolution, but I decode the corresponding latent with VAE of stabilityai/stable-diffusion-2-1-base. My remaining question is why the implementation use two different model for unet(stabilityai/stable-diffusion-2-1-base) and unet_lora(stabilityai/stable-diffusion-2-1)? But the rendered image is fixed to 512x512 resolution. Is it a special design?

**Comment by bennyguo** [comment]
The LoRA uses 2-1 as it is a v-prediction model, which performs better than epsilon prediction models. You can use 2-1 for the pretrained model too but you need to scale VAE input to 768x768, which consumes more memory and is slower to train.

**Comment by yuanzhi-zhu** [comment]
Hi @bennyguo ,

Have you tried 2-1-base as the v-prediction model (and also the pretrained model), is it slightly worser or much worser than as epsilon prediction models?
