### ISSUE TITLE
Community Discord

### ISSUE THREAD

**Issue by AntonBaumannDE** [threestudio-project/threestudio#147]
Hi! Have you considered opening a channel on Discord? Would be cool to see other peoples results and sharing best practices. 

Cheers
Anton

**Comment by bennyguo** [comment]
Thank you for the advice! We'll consider this :)

**Comment by santisy** [comment]
The discord channel has been outdated, please update it.

**Comment by bennyguo** [comment]
@santisy Thanks for reporting! Fixed.
