### ISSUE TITLE
About VSD loss in 2D playground

### ISSUE THREAD

**Issue by MontaEllis** [threestudio-project/threestudio#153]
Could you give an example about how to use VSD loss in 2D img?

**Comment by yuanzhi-zhu** [comment]
Hi @MontaEllis，

would you like to try this one I've just made :)

https://github.com/yuanzhi-zhu/prolific_dreamer2d

**Comment by thuliu-yt16** [comment]
Or you can try [vsd2d.py](https://github.com/threestudio-project/threestudio/blob/vsd2d/vsd2d.py), also see #100.
