### ISSUE TITLE
trying prolific dreamer with your command getting syntax error

### ISSUE THREAD

**Issue by IkuStudies** [threestudio-project/threestudio#155]
sorry i forgot a ! before the command.  stupid error.  tried to delete this issue can't find the delete button

**Comment by IkuStudies** [comment]
oh i'm an idiot haha i forgot the ! in the beginning.

also not that it matters too much but you might want to add !pip install wandb into the dependencies on the google colab

**Comment by DSaurus** [comment]
No problem! It happens to everyone. Don't worry, I will close this issue.
