### ISSUE TITLE
Error while using image-to-3d with arbitrary image with zero123

### ISSUE THREAD

**Issue by stas-polukeev** [threestudio-project/threestudio#156]
Hey there, thanks for the great work!
I'm trying to use image-to-3D with this code below:
python launch.py --config=configs/zero123.yaml data.image_path=/data/1.png --train 
I get this error in /threestudio/systems/zero123.py:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (36864x8 and 36864x8).
I suspect that the problem is that the image is not preprocessed and not in rgba format (because if I try with imgs from /load it works fine), but I couldn't find how to convert it to the required format.
Any help would be greaty appreciated.

**Comment by bennyguo** [comment]
Hi! You could use the [preprocessing script](https://github.com/ashawkey/stable-dreamfusion/blob/main/preprocess_image.py) from Stable-DreamFusion to get rgba, depth, and normal images. We'll add this script to threestudio later.

**Comment by stas-polukeev** [comment]
@bennyguo, thanks, I'll do that!
