### ISSUE TITLE
Render Normals/Geometry during NeRF Phase

### ISSUE THREAD

**Issue by ayaanzhaque** [threestudio-project/threestudio#167]
I am trying to view normals/geometry during VSD training. I see that some of the renders return the `comp_normal` in the batch, but I can't seem to get the NeRF renderer to do so. How can I do this?

**Comment by DSaurus** [comment]
Hi, @ayaanzhaque. You may consider using "hybrid-rgb-latent-material" in control4D branch, which will return ```comp_normal``` in the batch.

**Comment by bennyguo** [comment]
It's because normal_type is set to null in the config. Change it to analytic or finite_difference will make the renderer return comp_normal.

**Comment by DSaurus** [comment]
> It's because normal_type is set to null in the config. Change it to analytic or finite_difference will make the renderer return comp_normal.

Oh, I forget the normal_type.

**Comment by ayaanzhaque** [comment]
@bennyguo just swapping to "analytic" or "finite_difference" doesn't solve this problem. I want the saved images (e.g. it5000-0.png) to show 3 images, the rgb, normals, and depth. It seems the code supports that, but this flag alone doesn't solve the problem.
