### ISSUE TITLE
RuntimeError: CUDA out of memory for prolificdreamer when using the resolution of 512 on an A100 card(40G).

### ISSUE THREAD

**Issue by thucz** [threestudio-project/threestudio#170]
I tried to run prolificdreamer in the default scene setting like this on one A100 card (with 40G VRAM):
`python launch.py --config configs/prolificdreamer-scene.yaml --train --gpu 0 system.prompt_processor.prompt="Inside of a smart home, realistic detailed photo, 4k"
`

But I met the following error after 5000 iterations when the resolution became 512 from 64:
`RuntimeError: CUDA out of memory. Tried to allocate 4.41 GiB (GPU 0; 39.59 GiB total capacity; 19.44 GiB already allocated; 4.40 GiB free; 29.15 GiB reserved in total by PyTorch) If
reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Besides, I revised the resolution from 512 to 256, and it could run but took about 39G VRAM. I wonder why this happen.

**Comment by bennyguo** [comment]
Hi! Could you try reducing `system.renderer.num_samples_per_ray`? The progressive training strategy may not save as much VRAM for scenes as for objects as the scenes often occupy the whole screen space.

**Comment by thucz** [comment]
OK. Thanks!
