### ISSUE TITLE
Is it possible to finetune deepfloyd with Lora?

### ISSUE THREAD

**Issue by MrTornado24** [threestudio-project/threestudio#172]
As the title, can we replace stable diffusion by deepfloyd in prolificdreamer?

**Comment by DSaurus** [comment]
Hi, @MrTornado24. @thuliu-yt16 is working on deepfloyd+LORA, you can refer to https://github.com/threestudio-project/threestudio/issues/124 and https://github.com/threestudio-project/threestudio/tree/deepfloyd-vsd for more details.

**Comment by MrTornado24** [comment]
Thanks!
