### ISSUE TITLE
Weird normal map visulization result

### ISSUE THREAD

**Issue by buaacyw** [threestudio-project/threestudio#185]
Hi, thanks for your great repo! I have tried prolific-dreamer and get a nice result.
However, the normal map seems weird: 

https://github.com/threestudio-project/threestudio/assets/52091468/b4cc5667-7d87-47da-a0fc-43769bcadf04

![image](https://github.com/threestudio-project/threestudio/assets/52091468/2b922e2c-a948-4259-9f12-de176f444238)
![image](https://github.com/threestudio-project/threestudio/assets/52091468/f0e59126-c7e0-438d-bc4e-0b93bf541ddb)

Why the normal value changes so much on the other side? Shouldn't the normal value be about the same?
Is there an option to generate a normal map like this from Wiki:
![a8ceb3ce60dac7374ec485230e52c8b](https://github.com/threestudio-project/threestudio/assets/52091468/c698237b-ce2c-4dc6-8283-9d25e70ab4ef)

Thanks!

**Comment by bennyguo** [comment]
Hi! The visualized normal is world-space normal directions, while the normal map you're showing is tangent-space normal perturbations. Typically the tangent-space normal perturbations are applied on top of the word-space normal. Hope this is clear :)

**Comment by buaacyw** [comment]
I see, Thanks a lot!
