### ISSUE TITLE
load geometry from disk

### ISSUE THREAD

**Issue by de-gozaru** [threestudio-project/threestudio#203]
Hi,

Thank you for the amazing library.

For now, the way to load an existing geometry is to have a saved `.ckpt` model, and to use `geometry_convert_from` parameter.

Is there a way to load a geometry directly from disk, for example as a tetrahedral or sdf mesh?

Thank you in advance.

**Comment by bennyguo** [comment]
If you want to load customized geometry from disk, you can write a new geometry module. Notice that you may need to rewrite the `isosurface` to correctly extract the surfaces.
