### ISSUE TITLE
prolificdreamer stage1 genenrated incomplete pineapple

### ISSUE THREAD

**Issue by aiminsu** [threestudio-project/threestudio#210]
Thanks for your great work!

I am follwing your work and doing some experiments with prolificdreamer.
Here is the params i used during traing stage1, 
batch size: 1
width: 256
height: 256
prompt: "A pineapple"
background_type: "solid-color-background"
Other parms are kept the same with that in prolificdreamer.yaml.

And here is the rendered video,

https://github.com/threestudio-project/threestudio/assets/19482234/3c3f0f0e-57dd-4ec4-a3b7-24a8a531d8cb

One part of the pineapple looks pretty good, while the other part is missing. Do I need to modify other params for training and any ideas to solve this problem? Thanks in advance for your answer.

**Comment by bennyguo** [comment]
This could result from the using of `solid-color-background` as clearly the black background is treated as part of the foreground in some views. Could you try using the default background configuration (learned color + random color augmentation)?

**Comment by bennyguo** [comment]
This could result from the use of `solid-color-background` as clearly the black background is treated as part of the foreground in some views. Could you use the default background configuration (learned color + random color augmentation)?

**Comment by aiminsu** [comment]
Thanks, I tried default background configuration and it works!
