### ISSUE TITLE
prolificdreamer result is strange ...

### ISSUE THREAD

**Issue by jiarenyf** [threestudio-project/threestudio#230]
PROMPT: Cute little red cat sleeping on floor with window on background.
CONFIG: prolificdreamer-scene

https://github.com/threestudio-project/threestudio/assets/12405578/7ec56c47-b65e-4603-a81e-65aecfe40e16

The result is strange ...

**Comment by bennyguo** [comment]
This scene generation configuration is for scenes without foreground objects. If you want to generate scenes with both foreground objects and background, you may want to implement the "scene with a centric object" initialization as in Sec.4.2 in the ProlificDreamer paper:

<img width="609" alt="image" src="https://github.com/threestudio-project/threestudio/assets/19284678/b9ebd148-2d0e-43ba-aefb-fff9213d17c1">

**Comment by jiarenyf** [comment]
OK
