### ISSUE TITLE
eglGetDisplay() failed

### ISSUE THREAD

**Issue by MrTornado24** [threestudio-project/threestudio#231]
The environment is python 3.9 + cuda 11.7 + pytorch2.0.1 + nvdiffrast-0.3.1. When running NVDiffRasterizer, the initial error is `glutil.h fatal error: EGL/egl.h: No such file or directory.` 

Then I tried to fix it by running `sudo apt-get install libegl1-mesa-dev` referring to [https://zhuanlan.zhihu.com/p/536639015](url). However, there is another bug here:

`[F glutil.cpp:332] eglGetDisplay() failed`

How to fix it?

**Comment by bennyguo** [comment]
Setting up the GL environment can be tricky in some cases. You may want to use the CUDA context of nvdiffrast instead by setting `system.renderer.context_type=cuda`.

**Comment by MrTornado24** [comment]
@bennyguo Thanks for your advice. Yeah I tried it before, but the strange thing is that when I traIn a model with NVDiffRasterizer renderer, `system.renderer.context_type=cuda` works well. However, when I export the mesh, it doesn't work and `[F glutil.cpp:332] eglGetDisplay() failed` is still reported.

**Comment by bennyguo** [comment]
@MrTornado24 When exporting mesh assets, you also need to set `system.exporter.context_type=cuda` :)

**Comment by MrTornado24** [comment]
@bennyguo Solved! Thanks :)

**Comment by xiangli93** [comment]
> @bennyguo Thanks for your advice. Yeah I tried it before, but the strange thing is that when I traIn a model with NVDiffRasterizer renderer, `system.renderer.context_type=cuda` works well. However, when I export the mesh, it doesn't work and `[F glutil.cpp:332] eglGetDisplay() failed` is still reported.

"system.renderer.context_type=cuda"  where I would put that code he gave?

**Comment by xiangli93** [comment]
> @MrTornado24 When exporting mesh assets, you also need to set `system.exporter.context_type=cuda` :)

where I would put that code he gave?

**Comment by xiangli93** [comment]
> @MrTornado24 When exporting mesh assets, you also need to set `system.exporter.context_type=cuda` :)

I encountered the same issue on the server, but even after applying your method, the problem persists. How can I resolve it?
