### ISSUE TITLE
GPU0 is using much memory 0.0

### ISSUE THREAD

**Issue by jiarenyf** [threestudio-project/threestudio#239]
<img width="854" alt="image" src="https://github.com/threestudio-project/threestudio/assets/12405578/c92b1384-0fcf-431f-bd88-00b14f141807">

How to fix, help, please !

**Comment by thuliu-yt16** [comment]
What is your running command?

**Comment by jiarenyf** [comment]
python3 launch.py --train --config config/prolificdreamer-scene.yaml --gpu 0,1,2,3,4,5,6,7 system.prompt_processor.prompt="Inside of a smart home, realistic detailed photo, 4k" data.n_val_views=8

@thuliu-yt16

**Comment by thuliu-yt16** [comment]
The first GPU computes the text embedding in a spawned thread before optimization and then releases it. Did you observe the memory usage keep high or not? If you run the same command twice, what about the memory usage in the second run?
