### ISSUE TITLE
wrong pip version leads to failure installation

### ISSUE THREAD

**Issue by yuanzhi-zhu** [threestudio-project/threestudio#247]
I got ModuleNotFoundError: No module named 'torch' when installing ```pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2``` with the newest pip==23.2.1

And this problem can be solved by reinstalling pip==23.0.1

Could you please help verify this?

**Comment by bennyguo** [comment]
This is weird. This is largely a nerfacc problem, so I suggest you also post this in the nerfacc repo.
