### ISSUE TITLE
Prolific stage1 get weird color with large steps?

### ISSUE THREAD

**Issue by krNeko9t** [threestudio-project/threestudio#256]
using prolificdreamer-patch.yaml to launch the program with 25000 total steps. and before step 5600 it's fine. but after 8000, the result color breaks. And It seems happen is the latter steps no matter how many total steps it is (e.g. total 10000, then break in 4000 maybe)
I guess it's maybe the hyperparameter? I lower the  lambda_sparsity and the break show up a bit latter.
Example are here:
![it5600-0](https://github.com/threestudio-project/threestudio/assets/42951801/dab1330d-1a95-4b9b-8a2e-89f3dce6922c)
![it8000-0](https://github.com/threestudio-project/threestudio/assets/42951801/436fb349-26f4-4bc0-9594-66442467f83b)

**Comment by thuliu-yt16** [comment]
This problem does exist in some cases, mostly due to the annealing strategy (t~[0.02,0.98] -> [0.02, 0.5]). This may be a point for improvement, such as a better annealing strategy. You can try to increase the lower bound. I am not sure whether some recent works can improve it, e.g. TP-SDS.

**Comment by ARuiChen** [comment]
The time step range of [0.02, 0.5] may produce strange colors in some cases.
