### ISSUE TITLE
Weired green point occured in ProlificDreamer-scene training process

### ISSUE THREAD

**Issue by studying910** [threestudio-project/threestudio#259]
Hi, I currently follow your instructions of prolificdreamer to train a scene using the text prompt "Inside of a smart home, realistic detailed photo, 4k".

After the first stage of nerf training, I got weird results:

https://github.com/threestudio-project/threestudio/assets/78642067/d3537464-b367-4844-9541-9a645de55c46

After all three stages, the results become more weird:

https://github.com/threestudio-project/threestudio/assets/78642067/f337f656-ebd0-4e51-8d46-0fac1575c1d8

Any idea about it? Thx :)

**Comment by bennyguo** [comment]
The green floaters are scene-specific. It's probably because there're lots of green indicators in the generated `smart home` images.

The scene configuration is only for stage 1, so you cannot directly apply stage 2 or 3 after that.

**Comment by studying910** [comment]
> 

Thx. So will there be stage 2&3 configuraton for scene lately?

Also, I use the text prompt offered in the case here with the same hyperparameter setting:
<img width="724" alt="1" src="https://github.com/threestudio-project/threestudio/assets/78642067/c2f5ad8b-2e51-4348-abea-03fb4a6f151c">

I am wondering why is there a huge difference between mine and the results shown in here:
<img width="798" alt="2" src="https://github.com/threestudio-project/threestudio/assets/78642067/417bf58d-d9a1-4bd1-8629-66b56a51d309">

Should I tune any hyperparameters? Thx

**Comment by bennyguo** [comment]
> Thx. So will there be stage 2&3 configuraton for scene lately?
Not in the plan (and not in the ProlificDreamer paper either). Modeling scenes can be a lot harder than objects. I think this deserves a new paper.

> I am wondering why is there a huge difference between mine and the results shown in here:
I don't think there's a difference. I got these results with the default config file. Maybe try with different seeds? 😃

**Comment by studying910** [comment]
Thx. I think it is enough to close this issue :)
