### ISSUE TITLE
Can't start magic3d-fine stage - just no error and killed.

### ISSUE THREAD

**Issue by Pashtetickus** [threestudio-project/threestudio#271]
Hello.
I've set up env with docker like this:

```
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

ENV TORCH_CUDA_ARCH_LIST="8.0"
ENV TCNN_CUDA_ARCHITECTURES=80
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=${CUDA_HOME}/bin:/home/${USER_NAME}/.local/bin:${PATH}
ENV LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
ENV LIBRARY_PATH=${CUDA_HOME}/lib64/stubs:${LIBRARY_PATH}

# apt install by root user
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    pkg-config \
    build-essential \
    curl \
    git \
    libegl1-mesa-dev \
    libgl1-mesa-dev \
    libgles2-mesa-dev \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libglvnd0 \
    libgl1 \
    libglx0 \
    libegl1 \
    libgles2 \
    libglvnd-dev \
    cmake \
    python-is-python3 \
    python3.8-dev \
    python3-pip \
    wget \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# for GLEW
ENV LD_LIBRARY_PATH /usr/lib64:$LD_LIBRARY_PATH
# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility,graphics
# Default pyopengl to EGL for good headless rendering support
ENV PYOPENGL_PLATFORM egl

RUN pip install --upgrade pip setuptools ninja imageio-ffmpeg
RUN pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
RUN pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
RUN pip install git+https://github.com/NVlabs/tiny-cuda-nn.git#subdirectory=bindings/torch
RUN pip install git+https://github.com/NVlabs/nvdiffrast.git

COPY . /workspace/app
WORKDIR /workspace/app
```

And added these line to requirements.txt based on last issues and my needs:
```
transformers==4.28.1
bitsandbytes==0.38.1
pymeshlab
```

Also did this: `cp docker/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json` from nvdiffrast repo

`nvcc --version`:
![image](https://github.com/threestudio-project/threestudio/assets/46760758/2aaeb0ed-c641-4510-838b-b49c42b4fbc0)

And i run command like this:
`
python launch.py --config configs/magic3d-refine-sd.yaml --train --gpu 0 system.renderer.context_type=cuda system.prompt_processor.prompt={text} system.prompt_processor.use_perp_neg=true system.geometry_convert_from=outputs/magic3d-coarse-if/magic3d/ckpts/last.ckpt trainer.max_steps=50 tag=magic3d_fine use_timestamp=False seed=42`

And magic-3d-coarse works fine, but fine-stage do nothing:
![Screenshot_14](https://github.com/threestudio-project/threestudio/assets/46760758/c67eba3e-2490-4725-812b-66db38eaf81e)

It just hanging. If i delete this **Lock** file it just `Killed`.
![image](https://github.com/threestudio-project/threestudio/assets/46760758/ca880e5a-6f3e-495d-b359-106caaa2f753)

Do you have any suggestions where the problem might be? 

P.S. 
It worked before but then i did maybe an update from requirements or pulled from the repo and it died somehow.
 I tried different dockers - none of them helped better than this setup.

**Comment by bennyguo** [comment]
You probably ran out of memory. Could you please try running with `system.geometry.isosurface_resolution=32` and see if it works?

**Comment by Pashtetickus** [comment]
Looks like it isn't the problem. And i also tried it in Colab - it worked with the same req.txt but i can't figure out difference in environment if so):
![image](https://github.com/threestudio-project/threestudio/assets/46760758/792e6af2-3d65-485a-9281-3d1240bc253a)

**Comment by Pashtetickus** [comment]
[docker from threestudio repo](https://github.com/threestudio-project/threestudio/blob/main/docs/installation.md) also didn't help. Maybe i should try previous commits?

**Comment by bennyguo** [comment]
could you run the Fantasia3D system and see if it works? if not, also try `system.renderer.context_type=cuda`

**Comment by Pashtetickus** [comment]
I reinstalled the nvidia driver and CUDA, installed a new req.txt and now everything works. I think the problem was somewhere in the dependencies. Thanks for the help!
