### ISSUE TITLE
torch1.12.1+cu113 meets lighting 2.0.0

### ISSUE THREAD

**Issue by Bitterdhg** [threestudio-project/threestudio#280]
I use torch1.12.1+cu113, and lighting 2.0.0 must be compatible with torch2.0.0. So torch1.12.1+cu113 is not used if i want to train the model?

**Comment by bennyguo** [comment]
I think lightning2.0.0 works fine with torch1.12.1 (actually that's what I'm using most of the time)

**Comment by Bitterdhg** [comment]
Thanks for your reply. In the end, I solved the problem by installing Torch2.0.
