### ISSUE TITLE
 Could not find a version that satisfies the requirement embreex;

### ISSUE THREAD

**Issue by andytriboletti** [threestudio-project/threestudio#285]
I am using Ubuntu 20.04 now.

I got an error from pip install -r requirements.txt:

ERROR: Could not find a version that satisfies the requirement embreex; extra == "easy" (from trimesh[easy]->-r requirements.txt (line 18)) (from versions: none)
ERROR: No matching distribution found for embreex; extra == "easy" (from trimesh[easy]->-r requirements.txt (line 18))

**Comment by bennyguo** [comment]
you could simply replace `trimesh[easy]` with `trimesh` in the requirements

**Comment by andytriboletti** [comment]
Using this article I was able to install trimesh[easy] 

https://zenn.dev/shinya7y/articles/threestudio-prolificdreamer
