### ISSUE TITLE
Bug in classifier-free guidance in SDS?

### ISSUE THREAD

**Issue by MightyChaos** [threestudio-project/threestudio#289]
Is this a bug on the first term of the right-hand-side of the following line?
Should it be `noise_pred_uncond` instead of `noise_pred_text`, it does not make a big difference when the classifier guidance scale is large, i.e. 100, but it may become an issue when the scale is small, i.e. 7.5 ?
https://github.com/threestudio-project/threestudio/blob/0b96c7b8a4f0d9f7dad437aae1e3c5eadf5d74e1/threestudio/models/guidance/stable_diffusion_guidance.py#L249

**Comment by MightyChaos** [comment]
oh, they are equialent, only need to cancel the scale by 1.

**Comment by cfeng16** [comment]
I have the same quesiton, can you please clarify it futher?
