### ISSUE TITLE
different ways of reduction for vsd_loss and lora_loss

### ISSUE THREAD

**Issue by ziye3001** [threestudio-project/threestudio#290]
The reduction of vsd_loss is "sum", while the reduction for the lora_loss is "mean", which makes the these two losses differ by a multiple of 4*64*64. Is there a particular reason for the unbalanced losses? Thank you.

https://github.com/threestudio-project/threestudio/blob/0b96c7b8a4f0d9f7dad437aae1e3c5eadf5d74e1/threestudio/models/guidance/stable_diffusion_vsd_guidance.py#L652C9-L652C9

https://github.com/threestudio-project/threestudio/blob/0b96c7b8a4f0d9f7dad437aae1e3c5eadf5d74e1/threestudio/models/guidance/stable_diffusion_vsd_guidance.py#L584C12-L584C12

**Comment by thuliu-yt16** [comment]
We use the Adam optimizer. I think scaling the loss does not make much difference. Please correct me if wrong.

**Comment by ziye3001** [comment]
I see. You mean, since these two losses are for different parameters, the scaling actually does not matter. It makes sense. But I suspect that there are sort of dynamic balance between them during the optimization process. I will check if it really matters. Thank you. 

> We use the Adam optimizer. I think scaling the loss does not make much difference. Please correct me if wrong.

**Comment by thuliu-yt16** [comment]
I try both and did not see obvious differences. :)

**Comment by ziye3001** [comment]
well, I suppose you are right. thank you for the information.

**Comment by ziye3001** [comment]
close
