### ISSUE TITLE
Magic123, KeyError: 'zero123'

### ISSUE THREAD

**Issue by HL4214** [threestudio-project/threestudio#293]
Hi! I want to try the magic123 method. I run the launch.py used the commod 
`python launch.py --config configs/magic123-coarse-sd.yaml --train --gpu 0 data.image_path=load/images/hamburger_rgba.png system.prompt_processor.prompt="a delicious hamburger`.
but reported a problem that **KeyError: 'zero123'.** 
Through debug, I feel that zero123 is not registered in diffusers, but I don't know how to solve it.

**Comment by yf1019** [comment]
Hi, I met the same issue and I found it could be caused by the version of diffusers. I upgrade the diffusers from 0.16.0 to 0.20.0. And the problem disappears. 

If this doesn't solve the problem, you could also try to redownload the pretrained weights stored in ~/.cache/huggingface/.

**Comment by bennyguo** [comment]
@HL4214 You need to upgrade diffusers as pointed out by @yf1019 . I used the custom pipeline API which was introduced in newer versions.

**Comment by HL4214** [comment]
Ok,thanak you very much. I solved this problem by upgrading from 0.16.4 to 0.20.0 as pointed out by @yf1019.
