### ISSUE TITLE
Better preview?

### ISSUE THREAD

**Issue by mischaschaub** [threestudio-project/threestudio#299]
It would be super if the preview pictures would rotate a bit with each new picture, around 10 degrees, then we could see better if the 3D model is useable.  Or even a grid of preview views like left, bottom, top, angled.  Something to give a better indication of mesh quality.

**Comment by thuliu-yt16** [comment]
set data.n_val_views=4 for a four-way preview

**Comment by thuliu-yt16** [comment]
If you have a better idea, feel free to PR

**Comment by mischaschaub** [comment]
Many thanks, perfect solution!
