### ISSUE TITLE
Questions about `get_projection_matrix`

### ISSUE THREAD

**Issue by OrangeSodahub** [threestudio-project/threestudio#321]
Hi, it's a great work for me! And I'm confused about the function `get_projection_matrix`:
https://github.com/threestudio-project/threestudio/blob/607a4be985be817330b8ef79f817da6f255c14e5/threestudio/utils/ops.py#L266-L278
In the implementation of given dataset like `uncond`, it seems be the intrinsic matrix of generated camera sample, however the function is different from the normal K matrix formation I ever seen, especially the near, far. Could you give some advice or why here uses the projection matrix instead of normal camera intrinsic matrix? Thanks!

**Comment by DSaurus** [comment]
Hello @OrangeSodahub,  this function generates the projection matrix in OpenGL, which is distinct from the K matrix. For more detailed information, feel free to check out this link: https://amytabb.com/tips/tutorials/2019/06/28/OpenCV-to-OpenGL-tutorial-essentials/

**Comment by OrangeSodahub** [comment]
Thank! So I was wondering why you choose OpenGL's rule here, is there any pros and cons and high level of consideration? compared to OpenCV.

**Comment by DSaurus** [comment]
@OrangeSodahub , we chose OpenGL's rule because the NvDiff library utilizes an OpenGL camera. If your requirement is solely for neural representation, like NeRF, you don't need to worry about this aspect.

**Comment by OrangeSodahub** [comment]
Thanks, I'm just curious about it.
