### ISSUE TITLE
Multi-Face Problem Encountered?

### ISSUE THREAD

**Issue by vinwizardtoo** [threestudio-project/threestudio#349]
Hi! I'm new to 3D Vision and wasn't able to understand why ProlificDreamer was giving me this output per say? 
I ran the prolific dreamer model for 15k iterations and the geometry for 15k and texture model for 5k iterations.

Prompt: A zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes.

Please can you let me know what I'm missing?
https://github.com/threestudio-project/threestudio/assets/105859134/1cc3ecab-5d54-4cb2-8a4a-fc5eacf62859

**Comment by DSaurus** [comment]
Hi @vinwizardtoo ,

The VSD loss in Prolifcdreamer is unstable, which can easily lead to multi-face issues. You might consider combining it with some 3D guidance priors, such as Zero123 or MVDream.

**Comment by vinwizardtoo** [comment]
> Hi @vinwizardtoo ,
> 
> The VSD loss in Prolifcdreamer is unstable, which can easily lead to multi-face issues. You might consider combining it with some 3D guidance priors, such as Zero123 or MVDream.

Thanks a lot!
