### ISSUE TITLE
Generation Time

### ISSUE THREAD

**Issue by sekkit** [threestudio-project/threestudio#35]
How long does it cost to generate a 3d model?

**Comment by bennyguo** [comment]
It takes about ~30min for DreamFusion/Magic3D and ~15min for Latent-NeRF, SJC and Fantasia3D (geometry). All measured on a single RTX3090 with batch size 1 for 10000 iterations.

**Comment by sekkit** [comment]
which one produces the best result btw?

**Comment by bennyguo** [comment]
I would say `dreamfusion-if` and `magic3d-if`. The two perform differently, you could try both.

**Comment by sekkit** [comment]
thx a lot!

**Comment by sekkit** [comment]
I hope it supports output as 3d model(fbx or obj etc) files. Is that available?

**Comment by bennyguo** [comment]
On it 👨🏻‍💻 This is a high-priority feature!

**Comment by bennyguo** [comment]
> Can we train it off of other 3D models/pictures?

Do you mean if we can input a 3D model and get refined appearances/geometry on top of it?

**Comment by bennyguo** [comment]
@sekkit 
Hi! We now support exporting meshes! See [here](https://github.com/threestudio-project/threestudio#export-meshes) for more details.

![export-blender](https://github.com/threestudio-project/threestudio/assets/19284678/9067880e-bf0b-4881-a7a4-946d642adbb9)

**Comment by sekkit** [comment]
Wow!!!!!!!!!!!!!!!!!! thx.
