### ISSUE TITLE
Mesh extraction and start image guidance  

### ISSUE THREAD

**Issue by andorxornot** [threestudio-project/threestudio#37]
Good work!

Is there any way to extract mesh after training?
And another necessary feature is init image

**Comment by ThibaultGROUEIX** [comment]
+1 on mesh extraction for Magic3D.
This codebase is a gem. Congrats authors!

**Comment by thuliu-yt16** [comment]
Thank you! We are working on mesh extraction. And for image-conditioned generation, we already have an experimental version (see [imagecondition.yaml](https://github.com/threestudio-project/threestudio/blob/main/configs/experimental/imagecondition.yaml)).  We will further test and improve it. Please stay tuned!

**Comment by MrTornado24** [comment]
> Thank you! We are working on mesh extraction. And for image-conditioned generation, we already have an experimental version (see [imagecondition.yaml](https://github.com/threestudio-project/threestudio/blob/main/configs/experimental/imagecondition.yaml)). We will further test and improve it. Please stay tuned!

Hey, thanks for your awesome work! I tried `python launch.py --config configs/experimental/imagecondition.yaml --train --gpu 0` but there is an error: "AttributeError: 'ImplicitVolume' object has no attribute 'network'". What is the correct command for using image-condition generation?

**Comment by thuliu-yt16** [comment]
Sorry, we didn't update the config when we modified the implicit_volume class. You can simply replace L89-90 in imagecondition.yaml as follows:

Origin:
```yaml
    geometry.network:
        lr:0.005
```
Change to:
```yaml
    geometry.density_network:
        lr:0.005
    geometry.feature_network:
        lr:0.005
```
Now you can try it without error but good results are not guaranteed. We will update the implementation until we are ready to produce visually satisfying results. Also, contributions are welcome. Thanks a lot!

**Comment by bennyguo** [comment]
@ThibaultGROUEIX @andorxornot 
Hi! We now support exporting meshes! See [here](https://github.com/threestudio-project/threestudio#export-meshes) for more details.

![export-blender](https://github.com/threestudio-project/threestudio/assets/19284678/9067880e-bf0b-4881-a7a4-946d642adbb9)
