### ISSUE TITLE
TextMesh Implementation

### ISSUE THREAD

**Issue by bluestyle97** [threestudio-project/threestudio#38]
Thanks a lot for presenting this amazing project! Do you have any plan to implement the recent [TextMesh](https://arxiv.org/abs/2304.12439) paper and integrate it into threestudio? Looking forward to future updates!

**Comment by andorxornot** [comment]
Yes, that's a great article, using the sdf approach seems very logical. and also using several images from different camera angles as a loss to prevent color oversaturation

**Comment by bennyguo** [comment]
Hi @bluestyle97 @andorxornot ! Check out our new [feature request discussion](https://github.com/threestudio-project/threestudio/discussions/46) to submit your feature requests! We'll implement the most-wanted features/models once in a while :)

**Comment by bennyguo** [comment]
Hi @bluestyle97 @andorxornot , we've implemented the coarse stage of TextMesh. Please give it a try following [the instructions](https://github.com/threestudio-project/threestudio#textmesh-)!

**Comment by bennyguo** [comment]
I'll close this issue. If you have any questions experimenting with our TextMesh implementation, please feel free to reopen it.
