### ISSUE TITLE
Feature request : sanity checks of the SDS guidance losses on pixel optimizations

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [threestudio-project/threestudio#42]
Hi,

Awesome job on threestudio. 
I think it would be great to be able to run a sanity check on the SDS losses by running a very simple pixel optimization on a single image with the SDS loss. 
I think such an experiment would be very useful to tune the SDS parameters as well and understand their behaviour.
AFAIK, they have it in the original dreamfusion paper.

Cheers,
Thibault

**Comment by bennyguo** [comment]
Hi! We actually have it [here](https://github.com/threestudio-project/threestudio/blob/main/2dplayground.ipynb), however I'm not very sure it still works after all the refactor of the codebase :) will fix it soon!

**Comment by thuliu-yt16** [comment]
Hi Thibault,

Thanks for your suggestions! We already have a [2dplayground notebook](https://github.com/threestudio-project/threestudio/blob/main/2dplayground.ipynb) to test the guidance's behavior on 2D images. You can try it now. Feel free to post any feedback about potential improvements or bugs here. Hope this helps.

Yingtian

**Comment by ThibaultGROUEIX** [comment]
great to know !
I tried to run them and run into an error
![Screenshot 2023-05-13 at 15 31 53](https://github.com/threestudio-project/threestudio/assets/11445067/28b68901-a230-44a8-abc6-a20039758310)
Let me know if the solution is obvious, I'll look into it next week otherwize

**Comment by thuliu-yt16** [comment]
We also notice the error but the solution is not obvious. We are working on it and you may check it later. Please stay tuned.

**Comment by thuliu-yt16** [comment]
Bug fixed!

Conduct 2D experiments with either Stable Diffusion or DeepFloyd IF in our [2dplayground](https://github.com/threestudio-project/threestudio/blob/main/2dplayground.ipynb).

BTW, if you want to specify the used GPU, you can start the jupyter notebook server with `CUDA_VISIBLE_DEVICES=<gpu_ids>`.
