### ISSUE TITLE
Google Colab Notebook

### ISSUE THREAD

**Issue by qtabdullah** [threestudio-project/threestudio#47]
I dont have enough vram to run deep floyd if so i wish for a colab

**Comment by qtabdullah** [comment]
> Coming in a few days :)

lets go!

**Comment by bennyguo** [comment]
@qtabdullah Try our Colab notebook [here](https://colab.research.google.com/github/threestudio-project/threestudio/blob/main/threestudio.ipynb)! It is now just a simple wrapper, but at least you don't have to setup the environment locally :)

**Comment by qtabdullah** [comment]
> 

@bennyguo "from huggingface_hub import login

login()"
doesn't work

**Comment by bennyguo** [comment]
Could you provide a screenshot of the error message? @qtabdullah

**Comment by qtabdullah** [comment]
> Could you provide a screenshot of the error message? @qtabdullah

no error just a blank message

**Comment by qtabdullah** [comment]
see for your self

**Comment by bennyguo** [comment]
@qtabdullah Hi, I just fixed the issue. If you don't want to lose your current sessions, just replace `login` with `interpreter_login` in this block :)

**Comment by qtabdullah** [comment]
@bennyguo i got a error ERROR: Could not build wheels for nerfacc, which is required to install pyproject.toml-based projects
here is log ```Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
  Cloning https://github.com/KAIR-BAIR/nerfacc.git (to revision v0.5.2) to /tmp/pip-req-build-724kgdxu
  Running command git clone --filter=blob:none --quiet https://github.com/KAIR-BAIR/nerfacc.git /tmp/pip-req-build-724kgdxu
  Running command git checkout -q d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Resolved https://github.com/KAIR-BAIR/nerfacc.git to commit d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.10/dist-packages (from nerfacc==0.5.2) (13.3.4)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from nerfacc==0.5.2) (1.12.1)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=12->nerfacc==0.5.2) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=12->nerfacc==0.5.2) (2.14.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch->nerfacc==0.5.2) (4.5.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=12->nerfacc==0.5.2) (0.1.2)
Building wheels for collected packages: nerfacc
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for nerfacc (setup.py) ... error
  ERROR: Failed building wheel for nerfacc
  Running setup.py clean for nerfacc
Failed to build nerfacc
ERROR: Could not build wheels for nerfacc, which is required to install pyproject.toml-based projects
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/NVlabs/nvdiffrast.git
  Cloning https://github.com/NVlabs/nvdiffrast.git to /tmp/pip-req-build-_jkdkd3y
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/nvdiffrast.git /tmp/pip-req-build-_jkdkd3y
  Resolved https://github.com/NVlabs/nvdiffrast.git to commit 335cfa6b33d785730a04283994214bed57884e87
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from nvdiffrast==0.3.0) (1.22.4)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-wgyd93jo
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-wgyd93jo
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit a77dc53ed770dd8ea6f78951d5febe175d0045e9
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tinycudann
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tinycudann (setup.py) ... error
  ERROR: Failed building wheel for tinycudann
  Running setup.py clean for tinycudann
Failed to build tinycudann
ERROR: Could not build wheels for tinycudann, which is required to install pyproject.toml-based projects```

**Comment by qtabdullah** [comment]
i got an error here is log `Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
  Cloning https://github.com/KAIR-BAIR/nerfacc.git (to revision v0.5.2) to /tmp/pip-req-build-724kgdxu
  Running command git clone --filter=blob:none --quiet https://github.com/KAIR-BAIR/nerfacc.git /tmp/pip-req-build-724kgdxu
  Running command git checkout -q d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Resolved https://github.com/KAIR-BAIR/nerfacc.git to commit d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.10/dist-packages (from nerfacc==0.5.2) (13.3.4)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from nerfacc==0.5.2) (1.12.1)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=12->nerfacc==0.5.2) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=12->nerfacc==0.5.2) (2.14.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch->nerfacc==0.5.2) (4.5.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=12->nerfacc==0.5.2) (0.1.2)
Building wheels for collected packages: nerfacc
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for nerfacc (setup.py) ... error
  ERROR: Failed building wheel for nerfacc
  Running setup.py clean for nerfacc
Failed to build nerfacc
ERROR: Could not build wheels for nerfacc, which is required to install pyproject.toml-based projects
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/NVlabs/nvdiffrast.git
  Cloning https://github.com/NVlabs/nvdiffrast.git to /tmp/pip-req-build-_jkdkd3y
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/nvdiffrast.git /tmp/pip-req-build-_jkdkd3y
  Resolved https://github.com/NVlabs/nvdiffrast.git to commit 335cfa6b33d785730a04283994214bed57884e87
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from nvdiffrast==0.3.0) (1.22.4)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-wgyd93jo
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-wgyd93jo
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit a77dc53ed770dd8ea6f78951d5febe175d0045e9
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tinycudann
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tinycudann (setup.py) ... error
  ERROR: Failed building wheel for tinycudann
  Running setup.py clean for tinycudann
Failed to build tinycudann
ERROR: Could not build wheels for tinycudann, which is required to install pyproject.toml-based projects`

**Comment by bennyguo** [comment]
Could you run `pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2` as an individual command and give the error message?

**Comment by qtabdullah** [comment]
`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
  Cloning https://github.com/KAIR-BAIR/nerfacc.git (to revision v0.5.2) to /tmp/pip-req-build-k8uiv9fi
  Running command git clone --filter=blob:none --quiet https://github.com/KAIR-BAIR/nerfacc.git /tmp/pip-req-build-k8uiv9fi
  Running command git checkout -q d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Resolved https://github.com/KAIR-BAIR/nerfacc.git to commit d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.10/dist-packages (from nerfacc==0.5.2) (13.3.4)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from nerfacc==0.5.2) (1.12.1)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=12->nerfacc==0.5.2) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=12->nerfacc==0.5.2) (2.14.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch->nerfacc==0.5.2) (4.5.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=12->nerfacc==0.5.2) (0.1.2)
Building wheels for collected packages: nerfacc
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for nerfacc (setup.py) ... error
  ERROR: Failed building wheel for nerfacc
  Running setup.py clean for nerfacc
Failed to build nerfacc
ERROR: Could not build wheels for nerfacc, which is required to install pyproject.toml-based projects`

**Comment by qtabdullah** [comment]
> Could you run `pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2` as an individual command and give the error message?

`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
  Cloning https://github.com/KAIR-BAIR/nerfacc.git (to revision v0.5.2) to /tmp/pip-req-build-k8uiv9fi
  Running command git clone --filter=blob:none --quiet https://github.com/KAIR-BAIR/nerfacc.git /tmp/pip-req-build-k8uiv9fi
  Running command git checkout -q d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Resolved https://github.com/KAIR-BAIR/nerfacc.git to commit d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.10/dist-packages (from nerfacc==0.5.2) (13.3.4)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from nerfacc==0.5.2) (1.12.1)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=12->nerfacc==0.5.2) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=12->nerfacc==0.5.2) (2.14.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch->nerfacc==0.5.2) (4.5.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=12->nerfacc==0.5.2) (0.1.2)
Building wheels for collected packages: nerfacc
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for nerfacc (setup.py) ... error
  ERROR: Failed building wheel for nerfacc
  Running setup.py clean for nerfacc
Failed to build nerfacc
ERROR: Could not build wheels for nerfacc, which is required to install pyproject.toml-based projects`

**Comment by bennyguo** [comment]
Are you using colab? or are you on your own machine?

**Comment by qtabdullah** [comment]
> Are you using colab? or are you on your own machine?

colab

**Comment by bennyguo** [comment]
I haven't encountered such a problem on colab. What GPU model do you have? Could you give the output of `nvidia-smi`?

**Comment by qtabdullah** [comment]
> I haven't encountered such a problem on colab. What GPU model do you have? Could you give the output of `nvidia-smi`?

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by qtabdullah** [comment]
i mean it worked before

**Comment by qtabdullah** [comment]
but now it doesnt

**Comment by qtabdullah** [comment]
![it13000-0](https://github.com/threestudio-project/threestudio/assets/115927511/929a4b35-4b20-4586-9580-3279670d7101)

**Comment by bennyguo** [comment]
Did you try to restart the environment? simply just quit and reopen the colab url

**Comment by qtabdullah** [comment]
> Did you try to restart the environment? simply just quit and reopen the colab url

didnt work

**Comment by bennyguo** [comment]
Seems an issue related to incompatible PyTorch versions. Fixed in the latest commit. Please create a new environment and it should work now.

**Comment by xaranex1** [comment]
U need run this command: 

sudo apt update
sudo apt upgrade
sudo apt install libgl1-mesa-glx

**Comment by qtabdullah** [comment]
> Seems an issue related to incompatible PyTorch versions. Fixed in the latest commit. Please create a new environment and it should work now.

Traceback (most recent call last):
  File "/content/threestudio/launch.py", line 168, in <module>
    main()
  File "/content/threestudio/launch.py", line 69, in main
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities.imports import _SCIPY_AVAILABLE
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/__init__.py", line 1, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.utilities.data import select_topk, to_onehot
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/data.py", line 19, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 112, in <module>
    _TORCHVISION_GREATER_EQUAL_0_8: Optional[bool] = _compare_version("torchvision", operator.ge, "0.8.0")
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 78, in _compare_version
    if not _module_available(package):
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 59, in _module_available
    module = import_module(module_names[0])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/_optical_flow.py", line 12, in <module>
    from ..io.image import _read_png_16
  File "/usr/local/lib/python3.10/dist-packages/torchvision/io/__init__.py", line 8, in <module>
    from ._load_gpu_decoder import _HAS_GPU_VIDEO_DECODER
  File "/usr/local/lib/python3.10/dist-packages/torchvision/io/_load_gpu_decoder.py", line 1, in <module>
    from ..extension import _load_library
  File "/usr/local/lib/python3.10/dist-packages/torchvision/extension.py", line 107, in <module>
    _check_cuda_version()
  File "/usr/local/lib/python3.10/dist-packages/torchvision/extension.py", line 80, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.

**Comment by qtabdullah** [comment]
> > Seems an issue related to incompatible PyTorch versions. Fixed in the latest commit. Please create a new environment and it should work now.
> 
> Traceback (most recent call last): File "/content/threestudio/launch.py", line 168, in main() File "/content/threestudio/launch.py", line 69, in main import pytorch_lightning as pl File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/**init**.py", line 26, in from pytorch_lightning.callbacks import Callback # noqa: E402 File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/**init**.py", line 14, in from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in from pytorch_lightning.callbacks.callback import Callback File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in from pytorch_lightning.utilities.types import STEP_OUTPUT File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/types.py", line 25, in from torchmetrics import Metric File "/usr/local/lib/python3.10/dist-packages/torchmetrics/**init**.py", line 14, in from torchmetrics import functional # noqa: E402 File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/**init**.py", line 14, in from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/**init**.py", line 14, in from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate # noqa: F401 File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/pit.py", line 22, in from torchmetrics.utilities.imports import _SCIPY_AVAILABLE File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/**init**.py", line 1, in from torchmetrics.utilities.checks import check_forward_full_state_property # noqa: F401 File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/checks.py", line 25, in from torchmetrics.utilities.data import select_topk, to_onehot File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/data.py", line 19, in from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 112, in _TORCHVISION_GREATER_EQUAL_0_8: Optional[bool] = _compare_version("torchvision", operator.ge, "0.8.0") File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 78, in _compare_version if not _module_available(package): File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 59, in _module_available module = import_module(module_names[0]) File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/usr/local/lib/python3.10/dist-packages/torchvision/**init**.py", line 6, in from torchvision import datasets, io, models, ops, transforms, utils File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/**init**.py", line 1, in from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel File "/usr/local/lib/python3.10/dist-packages/torchvision/datasets/_optical_flow.py", line 12, in from ..io.image import _read_png_16 File "/usr/local/lib/python3.10/dist-packages/torchvision/io/**init**.py", line 8, in from ._load_gpu_decoder import _HAS_GPU_VIDEO_DECODER File "/usr/local/lib/python3.10/dist-packages/torchvision/io/_load_gpu_decoder.py", line 1, in from ..extension import _load_library File "/usr/local/lib/python3.10/dist-packages/torchvision/extension.py", line 107, in _check_cuda_version() File "/usr/local/lib/python3.10/dist-packages/torchvision/extension.py", line 80, in _check_cuda_version raise RuntimeError( RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.

@bennyguo

**Comment by bennyguo** [comment]
The colab environment comes with `torch2.0.1+cu118`. I noticed that when installing `xformers` it forces a reinstallation of `torch2.0.0` which is incompatible with `torchvision` comes with the environment ... I've removed `xformers` from the notebook as we don't need it anyway with `torch>=2.0.0`. Could you try again? Sorry for the inconvenience.

**Comment by claforte** [comment]
I recommend we close this issue since it's getting pretty long and it seems you solve most issues. People can open more precise issues if they encounter any.
