### ISSUE TITLE
DreamFusion Visual Gap and Error on "cannot load weights that are saved in int8"

### ISSUE THREAD

**Issue by alanyannick** [threestudio-project/threestudio#48]
Hi,

Thanks for the impressive work you have done on your repository. I did encounter an issue when attempting to change the configuration settings to use the IF setting. The error message stated that the weights I was trying to load were saved in int8 format and could not be loaded with load_in_8bit=True when using float32/float16/bfloat16 weights. 
> ValueError: ('You cannot load weights that are saved in int8 using load_in_8bit=True, make sure you are', ' using load_in_8bit=True on float32/float16/bfloat16 weights.')

I was able to resolve this issue by changing load_in_8bit to False and setting the variant to 'fp16', which should provide me with better guidance (ps: correct me if I am wrong :)); And I then ran the following configuration:
```
python launch.py --config configs/dreamfusion-if.yaml --train --gpu 0 system.prompt_processor.prompt="a tiger dressed as a doctor" system.background.random_aug=true
```

However, I noticed a visual discrepancy between my reproduced results and the results on your repository when using the prompt "a_tiger_dressed_as_a_doctor" from the Dreamfusion paper.

Here are my reproduced results:
![Screenshot from 2023-05-11 03-17-49](https://github.com/threestudio-project/threestudio/assets/12743884/5591031b-f8c7-41d5-a02b-179386909efe)
And here are the results on your repository:
![Screenshot from 2023-05-11 03-22-10](https://github.com/threestudio-project/threestudio/assets/12743884/9704191e-f9b1-434d-98c3-fc7ba8769fbe)

I was wondering if you could kindly let me know if there are any specific settings that I should follow in order to reproduce the following results from your repository. Any insights or suggestions would be greatly appreciated. 

![Screenshot from 2023-05-11 03-44-59](https://github.com/threestudio-project/threestudio/assets/12743884/b618281a-66dc-4984-82d4-4e4c38a7f562)

**Comment by claforte** [comment]
No response in 3 weeks... I hope no one minds if I close this issue.
