### ISSUE TITLE
Incorrect legs

### ISSUE THREAD

**Issue by sekkit** [threestudio-project/threestudio#53]
I tried dreamfusion method but produces three legs dinosaurs.
How to avoid that?

**Comment by bennyguo** [comment]
This is commonly referred to as the multi-face Janus problem. There's no solution to avoid that but you may try different seeds and will get correct results if you're lucky :) Also see [here](https://github.com/threestudio-project/threestudio#tips-on-improving-quality) for general tips on improving quality.
