### ISSUE TITLE
imagecondition train

### ISSUE THREAD

**Issue by andorxornot** [threestudio-project/threestudio#60]
I tried to train imagecondition exp with the IF model (because I couldn't set it up with SD), so I replaced the model in the config, and got an error in the "depth loss" line. So I disabled the "depth loss" , and the model after 50k step still doesn't look very much like the ref image

**Comment by andorxornot** [comment]
My prompt:" a marble sculpture of a young, handsome poet with long hair kneeling before God"
cond image: ![poet01](https://github.com/threestudio-project/threestudio/assets/33554420/3ca03647-acec-4941-b470-0408cc38f553)
result of 52000: ![it52000-0](https://github.com/threestudio-project/threestudio/assets/33554420/cd2e92b4-1daa-4d6c-b2c4-85bd240a7c05)

**Comment by zouzx** [comment]
Hi, our image-conditioned generation is still an experimental version, it indeed can’t make it like ref image very much for now. We are working on better image-conditioned results, please stay tuned.

**Comment by andorxornot** [comment]
thanks, I also pre-processed the image with the stable-dreamfusion script, so the depth loss works now, but the results are the same. 
i think the result is the same as without any the loss 

preprocessed: 
![img](https://github.com/threestudio-project/threestudio/assets/33554420/ab65fb76-fcf1-4d1f-b99f-e3224c800151)
46000: 
![it46000-0](https://github.com/threestudio-project/threestudio/assets/33554420/8f5a6096-83ea-41da-9075-168ad78856db)

**Comment by bennyguo** [comment]
Could you get better results with stable-dreamfusion image-to-3D? They did a lot of experiments on this.

**Comment by andorxornot** [comment]
yeah, i will try. it would also be good to add an image normal condition for `fantasia3d`, in my tests this model shows good results. unfortunately i am not very familiar with lightning

**Comment by andorxornot** [comment]
> I suggest you try [Make-It-3D](https://github.com/junshutang/Make-It-3D). It can produce results well aligned with the input image. By the way, Make-It-3D will come to threestudio soon, please stay tuned :)

trying Make-It-3D without coarse stage. nothing interesting, the same result as stable-dreamfusion
