### ISSUE TITLE
Increase iterations

### ISSUE THREAD

**Issue by xaranex1** [threestudio-project/threestudio#64]
How to increase iteration speed? on GPU RTX 3090 ?

**Comment by bennyguo** [comment]
If you are already using `data.batch_size=1`, there's no trivial way to speed up. You may try to enable token merging [described here](https://github.com/threestudio-project/threestudio#vram-optimization), but there's no guarantee that the results are the same. Also, it only works with stable diffusion guidance.

**Comment by claforte** [comment]
I've tried a bunch of things (e.g. decreasing system.renderer.num_samples_per_ray from 512 to 384) but all "easy" options resulted in noticeable degradation in quality. Closing.
