### ISSUE TITLE
Image-to-3D method?

### ISSUE THREAD

**Issue by WUMINGCHAzero** [threestudio-project/threestudio#65]
Is there any plan to implement image-to-3d method like Zero123?

Thanks!

**Comment by bennyguo** [comment]
Yes we're exploring a bunch of image-to-3D techniques. Stay tuned :)

**Comment by WUMINGCHAzero** [comment]
That's so great! Is there a specific time, like xx weeks?

**Comment by bennyguo** [comment]
Hopefully realfusion + make-it-3d in two weeks :)

**Comment by WUMINGCHAzero** [comment]
Thanks a lot!
