### ISSUE TITLE
Best GPU for training

### ISSUE THREAD

**Issue by xaranex1** [threestudio-project/threestudio#66]
You have some list of best GPUs for training?

**Comment by bennyguo** [comment]
RTX 3090/4080/4090 would be sufficient. But if you want a larger batch size, you'd need an A100 40GB/80GB.

**Comment by xaranex1** [comment]
Okay, i have only 3 iterations per second on A100 and 6 iterations per second on 3090 with batch size = 1 i tried change to token merging to true with SD but no results on iterations speed so i tried install tomesd library and restart kernel but nothing happen to me.
