### ISSUE TITLE
I cant use Magic3D refine from coarse stage IF

### ISSUE THREAD

**Issue by xaranex1** [threestudio-project/threestudio#67]
I cant use Magic3D refine from last.ckpt coarse stage IF... Only SD coarse stage working.

**Comment by bennyguo** [comment]
what's the error message? also please provide the command used to train the coarse stage and refinement stage.

**Comment by xaranex1** [comment]
!python launch.py --config configs/magic3d-refine-sd.yaml --train --gpu 0 system.prompt_processor.prompt="Michelangelo style bust of a Zeus" system.from_coarse=/root/threestudio/outputs/magic3d-coarse-if/Michelangelo_style_bust_of_a_Zeus/ckpts/last.ckpt


And error here:

[INFO] Initializing from coarse stage ...
[INFO] Automatically determined isosurface threshold: 20.142719268798828
[INFO] Automatically determined isosurface threshold: 38.54680252075195
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:1893 in  │
│ _run_ninja_build                                                             │
│                                                                              │
│   1890 │   │   # To work around this, we pass in the fileno directly and hop │
│   1891 │   │   # it is valid.                                                │
│   1892 │   │   stdout_fileno = 1                                             │
│ ❱ 1893 │   │   subprocess.run(                                               │
│   1894 │   │   │   command,                                                  │
│   1895 │   │   │   stdout=stdout_fileno if verbose else subprocess.PIPE,     │
│   1896 │   │   │   stderr=subprocess.STDOUT,                                 │
│                                                                              │
│ /usr/lib/python3.8/subprocess.py:516 in run                                  │
│                                                                              │
│    513 │   │   │   raise                                                     │
│    514 │   │   retcode = process.poll()                                      │
│    515 │   │   if check and retcode:                                         │
│ ❱  516 │   │   │   raise CalledProcessError(retcode, process.args,           │
│    517 │   │   │   │   │   │   │   │   │    output=stdout, stderr=stderr)    │
│    518 │   return CompletedProcess(process.args, retcode, stdout, stderr)    │
│    519                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /root/threestudio/launch.py:168 in <module>                                  │
│                                                                              │
│   165                                                                        │
│   166                                                                        │
│   167 if __name__ == "__main__":                                             │
│ ❱ 168 │   main()                                                             │
│   169                                                                        │
│                                                                              │
│ /root/threestudio/launch.py:107 in main                                      │
│                                                                              │
│   104 │   pl.seed_everything(cfg.seed)                                       │
│   105 │                                                                      │
│   106 │   dm = threestudio.find(cfg.data_type)(cfg.data)                     │
│ ❱ 107 │   system: BaseSystem = threestudio.find(cfg.system_type)(            │
│   108 │   │   cfg.system, resumed=cfg.resume is not None                     │
│   109 │   )                                                                  │
│   110 │   system.set_save_dir(os.path.join(cfg.trial_dir, "save"))           │
│                                                                              │
│ /root/threestudio/threestudio/systems/base.py:36 in __init__                 │
│                                                                              │
│    33 │   │   self._resumed: bool = resumed                                  │
│    34 │   │   self._resumed_eval: bool = False                               │
│    35 │   │   self._resumed_eval_status: dict = {"global_step": 0, "current_ │
│ ❱  36 │   │   self.configure()                                               │
│    37 │   │   if self.cfg.weights is not None:                               │
│    38 │   │   │   self.load_weights(self.cfg.weights, self.cfg.weights_ignor │
│    39 │   │   self.post_configure()                                          │
│                                                                              │
│ /root/threestudio/threestudio/systems/magic3d.py:80 in configure             │
│                                                                              │
│    77 │   │   else:                                                          │
│    78 │   │   │   self.geometry = threestudio.find(self.cfg.geometry_type)(s │
│    79 │   │                                                                  │
│ ❱  80 │   │   self.renderer = threestudio.find(self.cfg.renderer_type)(      │
│    81 │   │   │   self.cfg.renderer,                                         │
│    82 │   │   │   geometry=self.geometry,                                    │
│    83 │   │   │   material=self.material,                                    │
│                                                                              │
│ /root/threestudio/threestudio/utils/base.py:77 in __init__                   │
│                                                                              │
│   74 │   │   super().__init__()                                              │
│   75 │   │   self.cfg = parse_structured(self.Config, cfg)                   │
│   76 │   │   self.device = get_device()                                      │
│ ❱ 77 │   │   self.configure(*args, **kwargs)                                 │
│   78 │   │   if self.cfg.weights is not None:                                │
│   79 │   │   │   # format: path/to/weights:module_name                       │
│   80 │   │   │   weights_path, module_name = self.cfg.weights.split(":")     │
│                                                                              │
│ /root/threestudio/threestudio/models/renderers/nvdiff_rasterizer.py:32 in    │
│ configure                                                                    │
│                                                                              │
│   29 │   │   background: BaseBackground,                                     │
│   30 │   ) -> None:                                                          │
│   31 │   │   super().configure(geometry, material, background)               │
│ ❱ 32 │   │   self.ctx = NVDiffRasterizerContext(self.cfg.context_type, get_d │
│   33 │                                                                       │
│   34 │   def forward(                                                        │
│   35 │   │   self,                                                           │
│                                                                              │
│ /root/threestudio/threestudio/utils/rasterize.py:10 in __init__              │
│                                                                              │
│    7 class NVDiffRasterizerContext:                                          │
│    8 │   def __init__(self, context_type: str, device: torch.device) -> None │
│    9 │   │   self.device = device                                            │
│ ❱ 10 │   │   self.ctx = self.initialize_context(context_type, device)        │
│   11 │                                                                       │
│   12 │   def initialize_context(                                             │
│   13 │   │   self, context_type: str, device: torch.device                   │
│                                                                              │
│ /root/threestudio/threestudio/utils/rasterize.py:16 in initialize_context    │
│                                                                              │
│   13 │   │   self, context_type: str, device: torch.device                   │
│   14 │   ) -> Union[dr.RasterizeGLContext, dr.RasterizeCudaContext]:         │
│   15 │   │   if context_type == "gl":                                        │
│ ❱ 16 │   │   │   return dr.RasterizeGLContext(device=device)                 │
│   17 │   │   elif context_type == "cuda":                                    │
│   18 │   │   │   return dr.RasterizeCudaContext(device=device)               │
│   19 │   │   else:                                                           │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/nvdiffrast/torch/ops.py:221 in        │
│ __init__                                                                     │
│                                                                              │
│   218 │   │   else:                                                          │
│   219 │   │   │   with torch.cuda.device(device):                            │
│   220 │   │   │   │   cuda_device_idx = torch.cuda.current_device()          │
│ ❱ 221 │   │   self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrappe │
│   222 │   │   self.active_depth_peeler = None # For error checking only.     │
│   223 │                                                                      │
│   224 │   def set_context(self):                                             │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/nvdiffrast/torch/ops.py:118 in        │
│ _get_plugin                                                                  │
│                                                                              │
│   115 │                                                                      │
│   116 │   # Compile and load.                                                │
│   117 │   source_paths = [os.path.join(os.path.dirname(__file__), fn) for fn │
│ ❱ 118 │   torch.utils.cpp_extension.load(name=plugin_name, sources=source_pa │
│   119 │                                                                      │
│   120 │   # Import, cache, and return the compiled module.                   │
│   121 │   _cached_plugin[gl] = importlib.import_module(plugin_name)          │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:1284 in  │
│ load                                                                         │
│                                                                              │
│   1281 │   │   ...     extra_cflags=['-O2'],                                 │
│   1282 │   │   ...     verbose=True)                                         │
│   1283 │   '''                                                               │
│ ❱ 1284 │   return _jit_compile(                                              │
│   1285 │   │   name,                                                         │
│   1286 │   │   [sources] if isinstance(sources, str) else sources,           │
│   1287 │   │   extra_cflags,                                                 │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:1509 in  │
│ _jit_compile                                                                 │
│                                                                              │
│   1506 │   │   │   │   │   │                                                 │
│   1507 │   │   │   │   │   │   sources = list(hipified_sources)              │
│   1508 │   │   │   │   │                                                     │
│ ❱ 1509 │   │   │   │   │   _write_ninja_file_and_build_library(              │
│   1510 │   │   │   │   │   │   name=name,                                    │
│   1511 │   │   │   │   │   │   sources=sources,                              │
│   1512 │   │   │   │   │   │   extra_cflags=extra_cflags or [],              │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:1624 in  │
│ _write_ninja_file_and_build_library                                          │
│                                                                              │
│   1621 │                                                                     │
│   1622 │   if verbose:                                                       │
│   1623 │   │   print(f'Building extension module {name}...', file=sys.stderr │
│ ❱ 1624 │   _run_ninja_build(                                                 │
│   1625 │   │   build_directory,                                              │
│   1626 │   │   verbose,                                                      │
│   1627 │   │   error_prefix=f"Error building extension '{name}'")            │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:1909 in  │
│ _run_ninja_build                                                             │
│                                                                              │
│   1906 │   │   # mypy thinks it's Optional[BaseException] and doesn't narrow │
│   1907 │   │   if hasattr(error, 'output') and error.output:  # type: ignore │
│   1908 │   │   │   message += f": {error.output.decode(*SUBPROCESS_DECODE_AR │
│ ❱ 1909 │   │   raise RuntimeError(message) from e                            │
│   1910                                                                       │
│   1911                                                                       │
│   1912 def _get_exec_path(module_name, path):                                │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/4] c++ -MMD 
-MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl 
-DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" 
-DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include 
-isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem 
/usr/local/cuda/include -isystem /usr/include/python3.8 
-D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/torch/torch_rasterize_gl.cpp 
-o torch_rasterize_gl.o 
FAILED: torch_rasterize_gl.o 
c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl 
-DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" 
-DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include 
-isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem 
/usr/local/cuda/include -isystem /usr/include/python3.8 
-D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/torch/torch_rasterize_gl.cpp 
-o torch_rasterize_gl.o 
In file included from 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/torch/../common/rasterize_gl.h
:16,
                 from 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/torch/torch_rasterize_gl.cpp:1
2:
/usr/local/lib/python3.8/dist-packages/nvdiffrast/torch/../common/glutil.h:36:10
: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[2/4] c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl 
-DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" 
-DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include 
-isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem 
/usr/local/cuda/include -isystem /usr/include/python3.8 
-D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/rasterize_gl.cpp -o 
rasterize_gl.o 
FAILED: rasterize_gl.o 
c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl 
-DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" 
-DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include 
-isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem 
/usr/local/cuda/include -isystem /usr/include/python3.8 
-D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/rasterize_gl.cpp -o 
rasterize_gl.o 
In file included from 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/rasterize_gl.h:16,
                 from 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/rasterize_gl.cpp:9:
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/glutil.h:36:10: fatal 
error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[3/4] c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl 
-DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" 
-DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include 
-isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem 
/usr/local/cuda/include -isystem /usr/include/python3.8 
-D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
FAILED: glutil.o 
c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl 
-DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" 
-DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include 
-isystem /usr/local/lib/python3.8/dist-packages/torch/include/TH -isystem 
/usr/local/lib/python3.8/dist-packages/torch/include/THC -isystem 
/usr/local/cuda/include -isystem /usr/include/python3.8 
-D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
In file included from 
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/glutil.cpp:14:
/usr/local/lib/python3.8/dist-packages/nvdiffrast/common/glutil.h:36:10: fatal 
error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by bennyguo** [comment]
It could be some GL-related libraries missing from the colab environment. Could you try with `system.renderer.context_type=cuda` when refinement?

**Comment by xaranex1** [comment]
It working! thanks a lot!

**Comment by xaranex1** [comment]
Amazing project and work @bennyguo

**Comment by bennyguo** [comment]
Thank you! Closed.
