### ISSUE TITLE
Add support for Variational Score Distillation (VDS) proposed by ProlificDreamer？

### ISSUE THREAD

**Issue by WUMINGCHAzero** [threestudio-project/threestudio#73]
Recently [ProlificDreamer](https://arxiv.org/pdf/2305.16213.pdf) proposed to use Variational Score Distillation(VDS) to replace SDS function in dreamfusion, and it generates really great results. So, any plan to support it? It seems this could be applied to any text-to-3d or Image-to-3D methods to improve their results.

Thanks a lot!!!

**Comment by thuliu-yt16** [comment]
Working on it, stay tuned

**Comment by bennyguo** [comment]
Please try our experimental implementation following [the instruction](https://github.com/threestudio-project/threestudio#prolificdreamer-)!

**Comment by WUMINGCHAzero** [comment]
Thanks very very much!!
