### ISSUE TITLE
Is it possible to somehow remove the existing SD portion of this model with other fine-tuned SD models?

### ISSUE THREAD

**Issue by x-CK-x** [threestudio-project/threestudio#76]

**Comment by thuliu-yt16** [comment]
Do you mean to replace the stable diffusion with some specific fine-tuned SD model? If so, just replace the pre-trained model name or write a new class corresponding to that sd model if the interface is not compatible.

**Comment by x-CK-x** [comment]
yes. And thank you for the response, this is exactly what I was hoping for  :)
