### ISSUE TITLE
Text embedding file .threestudio_cache/text_embeddings/380af1c90b3b8ac914fde9dd32b144db.pt  not found

### ISSUE THREAD

**Issue by XinyangHan** [threestudio-project/threestudio#88]
Traceback (most recent call last):
  File "/home/xinyang/miniconda3/envs/3studio/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/xinyang/miniconda3/envs/3studio/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xinyang/threestudio/threestudio/models/prompt_processors/deepfloyd_prompt_processor.py", line 61, in spawn_func
    text_encoder = T5EncoderModel.from_pretrained(
  File "/home/xinyang/miniconda3/envs/3studio/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2722, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
                        
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/xinyang/threestudio/launch.py:180 in <module>                                              │
│                                                                                                  │
│   177                                                                                            │
│   178                                                                                            │
│   179 if __name__ == "__main__":                                                                 │
│ ❱ 180 │   main()                                                                                 │
│   181                                                                                            │
│                                                                                                  │
│ /home/xinyang/threestudio/launch.py:164 in main                                                  │
│                                                                                                  │
│   161 │   │   system.set_resume_status(ckpt["epoch"], ckpt["global_step"])                       │
│   162 │                                                                                          │
│   163 │   if args.train:                                                                         │
│ ❱ 164 │   │   trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)                           │
│   165 │   │   trainer.test(system, datamodule=dm)                                                │
│   166 │   elif args.validate:                                                                    │
│   167 │   │   # manually set epoch and global_step as they cannot be automatically resumed       │
│                                                                                                  │
│ /home/xinyang/miniconda3/envs/3studio/lib/python3.8/site-packages/pytorch_lightning/trainer/trai │
│ ner.py:520 in fit                                                                                │
│                                                                                                  │
│    517 │   │   """                                                                               │
│    518 │   │   model = _maybe_unwrap_optimized(model)                                            │
│    519 │   │   self.strategy._lightning_module = model                                           │
│ ❱  520 │   │   call._call_and_handle_interrupt(                                                  │
│    521 │   │   │   self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule,  │
│    522 │   │   )                                                                                 │
│    523                                                                                           │
│                                                                                                  │
│ /home/xinyang/miniconda3/envs/3studio/lib/python3.8/site-packages/pytorch_lightning/trainer/call │
│ .py:44 in _call_and_handle_interrupt                                                             │
│                                                                                                  │
│    41 │   │   if trainer.strategy.launcher is not None:                                          │
│    42 │   │   │   return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer,    │
│    43 │   │   else:                                                                              │
│ ❱  44 │   │   │   return trainer_fn(*args, **kwargs)                                             │
│    45 │                                                                                          │
│    46 │   except _TunerExitException:                                                            │
│    47 │   │   _call_teardown_hook(trainer)                                                       │
│                                                                                                  │
│ /home/xinyang/miniconda3/envs/3studio/lib/python3.8/site-packages/pytorch_lightning/trainer/trai │
│ ner.py:559 in _fit_impl                                                                          │
│                                                                                                  │
│    556 │   │   │   model_provided=True,                                                          │
│    557 │   │   │   model_connected=self.lightning_module is not None,                            │
│    558 │   │   )                                                                                 │
│ ❱  559 │   │   self._run(model, ckpt_path=ckpt_path)                                             │
│    560 │   │                                                                                     │
│    561 │   │   assert self.state.stopped                                                         │
│    562 │   │   self.training = False                                                             │
│                                                                                                  │
│ /home/xinyang/miniconda3/envs/3studio/lib/python3.8/site-packages/pytorch_lightning/trainer/trai │
│ ner.py:916 in _run                                                                               │
│                                                                                                  │
│    913 │   │   # hook                                                                            │
│    914 │   │   if self.state.fn == TrainerFn.FITTING:                                            │
│    915 │   │   │   call._call_callback_hooks(self, "on_fit_start")                               │
│ ❱  916 │   │   │   call._call_lightning_module_hook(self, "on_fit_start")                        │
│    917 │   │                                                                                     │
│    918 │   │   _log_hyperparams(self)                                                            │
│    919                                                                                           │
│                                                                                                  │
│ /home/xinyang/miniconda3/envs/3studio/lib/python3.8/site-packages/pytorch_lightning/trainer/call │
│ .py:142 in _call_lightning_module_hook                                                           │
│                                                                                                  │
│   139 │   pl_module._current_fx_name = hook_name                                                 │
│   140 │                                                                                          │
│   141 │   with trainer.profiler.profile(f"[LightningModule]{pl_module.__class__.__name__}.{hoo   │
│ ❱ 142 │   │   output = fn(*args, **kwargs)                                                       │
│   143 │                                                                                          │
│   144 │   # restore current_fx when nested context                                               │
│   145 │   pl_module._current_fx_name = prev_fx_name                                              │
│                                                                                                  │
│ /home/xinyang/threestudio/threestudio/systems/dreamfusion.py:32 in on_fit_start                  │
│                                                                                                  │
│    29 │   def on_fit_start(self) -> None:                                                        │
│    30 │   │   super().on_fit_start()                                                             │
│    31 │   │   # only used in training                                                            │
│ ❱  32 │   │   self.prompt_processor = threestudio.find(self.cfg.prompt_processor_type)(          │
│    33 │   │   │   self.cfg.prompt_processor                                                      │
│    34 │   │   )                                                                                  │
│    35 │   │   self.guidance = threestudio.find(self.cfg.guidance_type)(self.cfg.guidance)        │
│                                                                                                  │
│ /home/xinyang/threestudio/threestudio/utils/base.py:58 in __init__                               │
│                                                                                                  │
│   55 │   │   super().__init__()                                                                  │
│   56 │   │   self.cfg = parse_structured(self.Config, cfg)                                       │
│   57 │   │   self.device = get_device()                                                          │
│ ❱ 58 │   │   self.configure(*args, **kwargs)                                                     │
│   59 │                                                                                           │
│   60 │   def configure(self, *args, **kwargs) -> None:                                           │
│   61 │   │   pass                                                                                │
│                                                                                                  │
│ /home/xinyang/threestudio/threestudio/models/prompt_processors/base.py:190 in configure          │
│                                                                                                  │
│   187 │   │   ]                                                                                  │
│   188 │   │                                                                                      │
│   189 │   │   self.prepare_text_embeddings()                                                     │
│ ❱ 190 │   │   self.load_text_embeddings()                                                        │
│   191 │                                                                                          │
│   192 │   @staticmethod                                                                          │
│   193 │   def spawn_func(pretrained_model_name_or_path, prompts, cache_dir):                     │
│                                                                                                  │
│ /home/xinyang/threestudio/threestudio/models/prompt_processors/base.py:246 in                    │
│ load_text_embeddings                                                                             │
│                                                                                                  │
│   243 │   def load_text_embeddings(self):                                                        │
│   244 │   │   # synchronize, to ensure the text embeddings have been computed and saved to cac   │
│   245 │   │   barrier()                                                                          │
│ ❱ 246 │   │   self.text_embeddings = self.load_from_cache(self.prompt)[None, ...]                │
│   247 │   │   self.uncond_text_embeddings = self.load_from_cache(self.negative_prompt)[          │
│   248 │   │   │   None, ...                                                                      │
│   249 │   │   ]                                                                                  │
│                                                                                                  │
│ /home/xinyang/threestudio/threestudio/models/prompt_processors/base.py:264 in load_from_cache    │
│                                                                                                  │
│   261 │   │   │   f"{hash_prompt(self.cfg.pretrained_model_name_or_path, prompt)}.pt",           │
│   262 │   │   )                                                                                  │
│   263 │   │   if not os.path.exists(cache_path):                                                 │
│ ❱ 264 │   │   │   raise FileNotFoundError(                                                       │
│   265 │   │   │   │   f"Text embedding file {cache_path} for model {self.cfg.pretrained_model_   │
│   266 │   │   │   )                                                                              │
│   267 │   │   return torch.load(cache_path, map_location=self.device)                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: Text embedding file .threestudio_cache/text_embeddings/380af1c90b3b8ac914fde9dd32b144db.pt for model DeepFloyd/IF-I-XL-v1.0 and prompt [a zoomed
out DSLR photo of a baby bunny sitting on top of a stack of pancakes] not found.

**Comment by bennyguo** [comment]
Something went wrong during extracting text embeddings. Try again with `system.prompt_processor.spawn=false` and get more detailed error messages.

**Comment by suqingkun** [comment]
I think it is because you have not logged in huggingface using `huggingface-cli login`. After running this cmd, the problem is fixed on my environment.

**Comment by garychan22** [comment]
@suqingkun thanks for your kindly comment, I have logged in huggingface following
```
from huggingface_hub import login
login()
```
however, the problem still exists.

Could you share your env list for pip packages? I am wondering the reason is the incompatible dependencies. Thanks a lot!

**Comment by suqingkun** [comment]
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
accelerate                0.19.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.7.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bitsandbytes              0.39.0                   pypi_0    pypi
blessed                   1.20.0                   pypi_0    pypi
ca-certificates           2023.01.10           h06a4308_0  
cachetools                5.3.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
chardet                   5.1.0                    pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
clip                      1.0                      pypi_0    pypi
cmake                     3.26.3                   pypi_0    pypi
colorlog                  6.7.0                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
croniter                  1.3.15                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dateutils                 0.6.12                   pypi_0    pypi
deepdiff                  6.3.0                    pypi_0    pypi
diffusers                 0.16.1                   pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
embreex                   2.17.7.post1             pypi_0    pypi
exceptiongroup            1.1.1                    pypi_0    pypi
fastapi                   0.88.0                   pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.5.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
google-auth               2.19.1                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
huggingface-hub           0.15.1                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.31.0                   pypi_0    pypi
imageio-ffmpeg            0.4.8                    pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
inquirer                  3.1.3                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jaxtyping                 0.2.20                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kornia                    0.6.12                   pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libigl                    2.4.1                    pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1  
lightning                 2.0.0                    pypi_0    pypi
lightning-cloud           0.5.36                   pypi_0    pypi
lightning-utilities       0.8.0                    pypi_0    pypi
lit                       16.0.5.post0             pypi_0    pypi
lxml                      4.9.2                    pypi_0    pypi
mapbox-earcut             1.0.1                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nerfacc                   0.5.2                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
nvdiffrast                0.3.0                    pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
ordered-set               4.1.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1           py39h06a4308_0  
protobuf                  4.23.2                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pybind11                  2.11.0.dev1              pypi_0    pypi
pycollada                 0.7.2                    pypi_0    pypi
pydantic                  1.10.8                   pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyjwt                     2.7.0                    pypi_0    pypi
pymcubes                  0.1.4                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyre-extensions           0.0.29                   pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysdf                     0.1.8                    pypi_0    pypi
python                    3.9.16               h7a1cb2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
python-editor             1.0.4                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytorch-lightning         2.0.2                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readchar                  4.0.5                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2023.6.3                 pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      13.4.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
rtree                     1.0.1                    pypi_0    pypi
safetensors               0.3.1                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.25.0                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                67.8.0           py39h06a4308_0  
shapely                   2.0.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
starlette                 0.22.0                   pypi_0    pypi
starsessions              1.3.0                    pypi_0    pypi
svg-path                  6.3                      pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
taming-transformers-rom1504 0.0.6                    pypi_0    pypi
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tinycudann                1.7                      pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
transformers              4.29.2                   pypi_0    pypi
trimesh                   3.22.0                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typeguard                 4.0.0                    pypi_0    pypi
typing-extensions         4.6.3                    pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.16                  pypi_0    pypi
uvicorn                   0.22.0                   pypi_0    pypi
wandb                     0.15.3                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
websocket-client          1.5.2                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0  
xatlas                    0.0.7                    pypi_0    pypi
xformers                  0.0.20                   pypi_0    pypi
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by bennyguo** [comment]
Is this solved? Could you share how? I'm very curious 👀

**Comment by garychan22** [comment]
@bennyguo after I have rebuilt the whole environment to match the list and login the huggingface, the error still exists. 

this error is raised from `threestudio/models/prompt_processors/base.py:233`:
```
self.text_embeddings = self.load_from_cache(self.prompt)[None, ...]
```
it seems that the text embedding is accessed before the prompt being processed.

**Comment by andrewyguo** [comment]
Anyone find a solution to this error?

**Comment by aiexplorertpk** [comment]
I'm facing the same issue

**Comment by andrewyguo** [comment]
@aiexplorertpk  I referenced this solution: https://github.com/threestudio-project/threestudio/issues/148#issuecomment-1595735621
