### ISSUE TITLE
Can‘t use IF model

### ISSUE THREAD

**Issue by MontaEllis** [threestudio-project/threestudio#94]
Thanks for your great works! But I'm facing an error.

While running

python launch.py --config configs/dreamfusion-if.yaml --train --gpu 0 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes"

get an error. 

![image](https://github.com/threestudio-project/threestudio/assets/37856372/4d222726-4c04-4020-8302-29b344599260)

transformers, bitsandbytes are all updated to the newest ones.

**Comment by bennyguo** [comment]
It results from something from your old environment. We highly recommend a clean install in a new virtual environment.
